CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS account, artist, album, genre, track, audio_feature, temporal_feature, tag, playlist, rank_track, rank_artist, license, track_genre, track_tag, artist_tag, album_artist, track_artist_main, track_artist_feat, track_license, playlist_track, "user", preference, playlist_user, track_user_like, track_user_listen CASCADE;

CREATE TABLE account (
    account_id UUID DEFAULT uuid_generate_v4(),
    login VARCHAR(255),
    password VARCHAR(255),
    name VARCHAR(255),
    email VARCHAR(255),
    created_at TIMESTAMP,
    PRIMARY KEY (account_id)
);

CREATE TABLE artist (
    artist_id UUID DEFAULT uuid_generate_v4(),
    artist_bio TEXT,
    artist_location VARCHAR(255),
    artist_latitude DOUBLE PRECISION,
    artist_longitude DOUBLE PRECISION,
    artist_active_year_begin INTEGER,
    artist_active_year_end INTEGER,
    artist_favorites BIGINT,
    artist_comments BIGINT,
    PRIMARY KEY (artist_id),
    FOREIGN KEY (artist_id) REFERENCES account(account_id)
);

CREATE TABLE album (
    album_id UUID DEFAULT uuid_generate_v4(),
    album_title VARCHAR(255),
    album_type VARCHAR(255),
    album_tracks_count INTEGER,
    album_date_released DATE,
    album_listens BIGINT,
    album_favorites BIGINT,
    album_comments BIGINT,
    album_producer VARCHAR(255),
    PRIMARY KEY (album_id)
);

CREATE TABLE genre (
    genre_id UUID DEFAULT uuid_generate_v4(),
    parent_id UUID,
    title VARCHAR(255),
    top_level INTEGER,
    PRIMARY KEY (genre_id),
    FOREIGN KEY (parent_id) REFERENCES genre(genre_id)
);

CREATE TABLE track (
    track_id UUID DEFAULT uuid_generate_v4(),
    album_id UUID,
    track_title VARCHAR(255),
    track_duration BIGINT,
    track_number INTEGER,
    track_disc_number INTEGER,
    track_explicit BOOLEAN,
    track_instrumental BOOLEAN,
    track_listens BIGINT,
    track_favorites BIGINT,
    track_interest DOUBLE PRECISION,
    track_comments BIGINT,
    track_date_created DATE,
    track_composer VARCHAR(255),
    track_lyricist VARCHAR(255),
    track_publisher VARCHAR(255),
    PRIMARY KEY (track_id),
    FOREIGN KEY (album_id) REFERENCES album(album_id)
);

CREATE TABLE audio_feature (
    track_id UUID,
    acousticness DOUBLE PRECISION,
    danceability DOUBLE PRECISION,
    energy DOUBLE PRECISION,
    instrumentalness DOUBLE PRECISION,
    liveness DOUBLE PRECISION,
    speechiness DOUBLE PRECISION,
    tempo DOUBLE PRECISION,
    valence DOUBLE PRECISION,
    PRIMARY KEY (track_id),
    FOREIGN KEY (track_id) REFERENCES track(track_id)
);

CREATE TABLE temporal_feature (
    track_id UUID,
    chroma_stft_skew1 DOUBLE PRECISION,
    chroma_stft_skew2 DOUBLE PRECISION,
    chroma_stft_skew3 DOUBLE PRECISION,
    chroma_stft_skew4 DOUBLE PRECISION,
    chroma_stft_skew5 DOUBLE PRECISION,
    chroma_stft_skew6 DOUBLE PRECISION,
    chroma_stft_skew7 DOUBLE PRECISION,
    chroma_stft_skew8 DOUBLE PRECISION,
    chroma_stft_skew9 DOUBLE PRECISION,
    chroma_stft_skew10 DOUBLE PRECISION,
    chroma_stft_skew11 DOUBLE PRECISION,
    chroma_stft_std DOUBLE PRECISION,
    chroma_stft_std1 DOUBLE PRECISION,
    chroma_stft_std2 DOUBLE PRECISION,
    chroma_stft_std3 DOUBLE PRECISION,
    chroma_stft_std4 DOUBLE PRECISION,
    chroma_stft_std5 DOUBLE PRECISION,
    chroma_stft_std6 DOUBLE PRECISION,
    chroma_stft_std7 DOUBLE PRECISION,
    chroma_stft_std8 DOUBLE PRECISION,
    chroma_stft_std9 DOUBLE PRECISION,
    chroma_stft_std10 DOUBLE PRECISION,
    chroma_stft_std11 DOUBLE PRECISION,
    mfcc_kurtosis DOUBLE PRECISION,
    mfcc_kurtosis1 DOUBLE PRECISION,
    mfcc_kurtosis2 DOUBLE PRECISION,
    mfcc_kurtosis3 DOUBLE PRECISION,
    mfcc_kurtosis4 DOUBLE PRECISION,
    mfcc_kurtosis5 DOUBLE PRECISION,
    mfcc_kurtosis6 DOUBLE PRECISION,
    mfcc_kurtosis7 DOUBLE PRECISION,
    mfcc_kurtosis8 DOUBLE PRECISION,
    mfcc_kurtosis9 DOUBLE PRECISION,
    mfcc_kurtosis10 DOUBLE PRECISION,
    mfcc_kurtosis11 DOUBLE PRECISION,
    mfcc_kurtosis12 DOUBLE PRECISION,
    mfcc_kurtosis13 DOUBLE PRECISION,
    mfcc_kurtosis14 DOUBLE PRECISION,
    mfcc_kurtosis15 DOUBLE PRECISION,
    mfcc_kurtosis16 DOUBLE PRECISION,
    mfcc_kurtosis17 DOUBLE PRECISION,
    mfcc_kurtosis18 DOUBLE PRECISION,
    mfcc_kurtosis19 DOUBLE PRECISION,
    mfcc_max DOUBLE PRECISION,
    mfcc_max1 DOUBLE PRECISION,
    mfcc_max2 DOUBLE PRECISION,
    mfcc_max3 DOUBLE PRECISION,
    mfcc_max4 DOUBLE PRECISION,
    mfcc_max5 DOUBLE PRECISION,
    mfcc_max6 DOUBLE PRECISION,
    mfcc_max7 DOUBLE PRECISION,
    mfcc_max8 DOUBLE PRECISION,
    mfcc_max9 DOUBLE PRECISION,
    mfcc_max10 DOUBLE PRECISION,
    mfcc_max11 DOUBLE PRECISION,
    mfcc_max12 DOUBLE PRECISION,
    mfcc_max13 DOUBLE PRECISION,
    mfcc_max14 DOUBLE PRECISION,
    mfcc_max15 DOUBLE PRECISION,
    mfcc_max16 DOUBLE PRECISION,
    mfcc_max17 DOUBLE PRECISION,
    mfcc_max18 DOUBLE PRECISION,
    mfcc_max19 DOUBLE PRECISION,
    mfcc_mean DOUBLE PRECISION,
    mfcc_mean1 DOUBLE PRECISION,
    mfcc_mean2 DOUBLE PRECISION,
    mfcc_mean3 DOUBLE PRECISION,
    mfcc_mean4 DOUBLE PRECISION,
    mfcc_mean5 DOUBLE PRECISION,
    mfcc_mean6 DOUBLE PRECISION,
    mfcc_mean7 DOUBLE PRECISION,
    mfcc_mean8 DOUBLE PRECISION,
    mfcc_mean9 DOUBLE PRECISION,
    mfcc_mean10 DOUBLE PRECISION,
    mfcc_mean11 DOUBLE PRECISION,
    mfcc_mean12 DOUBLE PRECISION,
    mfcc_mean13 DOUBLE PRECISION,
    mfcc_mean14 DOUBLE PRECISION,
    mfcc_mean15 DOUBLE PRECISION,
    mfcc_mean16 DOUBLE PRECISION,
    mfcc_mean17 DOUBLE PRECISION,
    mfcc_mean18 DOUBLE PRECISION,
    mfcc_mean19 DOUBLE PRECISION,
    mfcc_median DOUBLE PRECISION,
    mfcc_median1 DOUBLE PRECISION,
    mfcc_median2 DOUBLE PRECISION,
    mfcc_median3 DOUBLE PRECISION,
    mfcc_median4 DOUBLE PRECISION,
    mfcc_median5 DOUBLE PRECISION,
    mfcc_median6 DOUBLE PRECISION,
    mfcc_median7 DOUBLE PRECISION,
    mfcc_median8 DOUBLE PRECISION,
    mfcc_median9 DOUBLE PRECISION,
    mfcc_median10 DOUBLE PRECISION,
    mfcc_median11 DOUBLE PRECISION,
    mfcc_median12 DOUBLE PRECISION,
    mfcc_median13 DOUBLE PRECISION,
    mfcc_median14 DOUBLE PRECISION,
    mfcc_median15 DOUBLE PRECISION,
    mfcc_median16 DOUBLE PRECISION,
    mfcc_median17 DOUBLE PRECISION,
    mfcc_median18 DOUBLE PRECISION,
    mfcc_median19 DOUBLE PRECISION,
    mfcc_min DOUBLE PRECISION,
    mfcc_min1 DOUBLE PRECISION,
    mfcc_min2 DOUBLE PRECISION,
    mfcc_min3 DOUBLE PRECISION,
    mfcc_min4 DOUBLE PRECISION,
    mfcc_min5 DOUBLE PRECISION,
    mfcc_min6 DOUBLE PRECISION,
    mfcc_min7 DOUBLE PRECISION,
    mfcc_min8 DOUBLE PRECISION,
    mfcc_min9 DOUBLE PRECISION,
    mfcc_min10 DOUBLE PRECISION,
    mfcc_min11 DOUBLE PRECISION,
    mfcc_min12 DOUBLE PRECISION,
    mfcc_min13 DOUBLE PRECISION,
    mfcc_min14 DOUBLE PRECISION,
    mfcc_min15 DOUBLE PRECISION,
    mfcc_min16 DOUBLE PRECISION,
    mfcc_min17 DOUBLE PRECISION,
    mfcc_min18 DOUBLE PRECISION,
    mfcc_min19 DOUBLE PRECISION,
    mfcc_skew DOUBLE PRECISION,
    mfcc_skew1 DOUBLE PRECISION,
    mfcc_skew2 DOUBLE PRECISION,
    mfcc_skew3 DOUBLE PRECISION,
    mfcc_skew4 DOUBLE PRECISION,
    mfcc_skew5 DOUBLE PRECISION,
    mfcc_skew6 DOUBLE PRECISION,
    mfcc_skew7 DOUBLE PRECISION,
    mfcc_skew8 DOUBLE PRECISION,
    mfcc_skew9 DOUBLE PRECISION,
    mfcc_skew10 DOUBLE PRECISION,
    mfcc_skew11 DOUBLE PRECISION,
    mfcc_skew12 DOUBLE PRECISION,
    mfcc_skew13 DOUBLE PRECISION,
    mfcc_skew14 DOUBLE PRECISION,
    mfcc_skew15 DOUBLE PRECISION,
    mfcc_skew16 DOUBLE PRECISION,
    mfcc_skew17 DOUBLE PRECISION,
    mfcc_skew18 DOUBLE PRECISION,
    mfcc_skew19 DOUBLE PRECISION,
    mfcc_std DOUBLE PRECISION,
    mfcc_std1 DOUBLE PRECISION,
    mfcc_std2 DOUBLE PRECISION,
    mfcc_std3 DOUBLE PRECISION,
    mfcc_std4 DOUBLE PRECISION,
    mfcc_std5 DOUBLE PRECISION,
    mfcc_std6 DOUBLE PRECISION,
    mfcc_std7 DOUBLE PRECISION,
    mfcc_std8 DOUBLE PRECISION,
    mfcc_std9 DOUBLE PRECISION,
    mfcc_std10 DOUBLE PRECISION,
    mfcc_std11 DOUBLE PRECISION,
    mfcc_std12 DOUBLE PRECISION,
    mfcc_std13 DOUBLE PRECISION,
    mfcc_std14 DOUBLE PRECISION,
    mfcc_std15 DOUBLE PRECISION,
    mfcc_std16 DOUBLE PRECISION,
    mfcc_std17 DOUBLE PRECISION,
    mfcc_std18 DOUBLE PRECISION,
    mfcc_std19 DOUBLE PRECISION,
    rmse_kurtosis DOUBLE PRECISION,
    rmse_max DOUBLE PRECISION,
    rmse_mean DOUBLE PRECISION,
    rmse_median DOUBLE PRECISION,
    rmse_min DOUBLE PRECISION,
    rmse_skew DOUBLE PRECISION,
    rmse_std DOUBLE PRECISION,
    spectral_bandwidth_kurtosis DOUBLE PRECISION,
    spectral_bandwidth_max DOUBLE PRECISION,
    spectral_bandwidth_mean DOUBLE PRECISION,
    spectral_bandwidth_median DOUBLE PRECISION,
    spectral_bandwidth_min DOUBLE PRECISION,
    spectral_bandwidth_skew DOUBLE PRECISION,
    spectral_bandwidth_std DOUBLE PRECISION,
    spectral_centroid_kurtosis DOUBLE PRECISION,
    spectral_centroid_max DOUBLE PRECISION,
    spectral_centroid_mean DOUBLE PRECISION,
    spectral_centroid_median DOUBLE PRECISION,
    spectral_centroid_min DOUBLE PRECISION,
    spectral_centroid_skew DOUBLE PRECISION,
    spectral_centroid_std DOUBLE PRECISION,
    spectral_contrast_kurtosis DOUBLE PRECISION,
    spectral_contrast_kurtosis1 DOUBLE PRECISION,
    spectral_contrast_kurtosis2 DOUBLE PRECISION,
    spectral_contrast_kurtosis3 DOUBLE PRECISION,
    spectral_contrast_kurtosis4 DOUBLE PRECISION,
    spectral_contrast_kurtosis5 DOUBLE PRECISION,
    spectral_contrast_kurtosis6 DOUBLE PRECISION,
    spectral_contrast_max DOUBLE PRECISION,
    spectral_contrast_max1 DOUBLE PRECISION,
    spectral_contrast_max2 DOUBLE PRECISION,
    spectral_contrast_max3 DOUBLE PRECISION,
    spectral_contrast_max4 DOUBLE PRECISION,
    spectral_contrast_max5 DOUBLE PRECISION,
    spectral_contrast_max6 DOUBLE PRECISION,
    spectral_contrast_mean DOUBLE PRECISION,
    spectral_contrast_mean1 DOUBLE PRECISION,
    spectral_contrast_mean2 DOUBLE PRECISION,
    spectral_contrast_mean3 DOUBLE PRECISION,
    spectral_contrast_mean4 DOUBLE PRECISION,
    spectral_contrast_mean5 DOUBLE PRECISION,
    spectral_contrast_mean6 DOUBLE PRECISION,
    spectral_contrast_median DOUBLE PRECISION,
    spectral_contrast_median1 DOUBLE PRECISION,
    spectral_contrast_median2 DOUBLE PRECISION,
    spectral_contrast_median3 DOUBLE PRECISION,
    spectral_contrast_median4 DOUBLE PRECISION,
    spectral_contrast_median5 DOUBLE PRECISION,
    spectral_contrast_median6 DOUBLE PRECISION,
    spectral_contrast_min DOUBLE PRECISION,
    spectral_contrast_min1 DOUBLE PRECISION,
    spectral_contrast_min2 DOUBLE PRECISION,
    spectral_contrast_min3 DOUBLE PRECISION,
    spectral_contrast_min4 DOUBLE PRECISION,
    spectral_contrast_min5 DOUBLE PRECISION,
    spectral_contrast_min6 DOUBLE PRECISION,
    spectral_contrast_skew DOUBLE PRECISION,
    spectral_contrast_skew1 DOUBLE PRECISION,
    spectral_contrast_skew2 DOUBLE PRECISION,
    spectral_contrast_skew3 DOUBLE PRECISION,
    spectral_contrast_skew4 DOUBLE PRECISION,
    spectral_contrast_skew5 DOUBLE PRECISION,
    spectral_contrast_skew6 DOUBLE PRECISION,
    spectral_contrast_std DOUBLE PRECISION,
    spectral_contrast_std1 DOUBLE PRECISION,
    spectral_contrast_std2 DOUBLE PRECISION,
    spectral_contrast_std3 DOUBLE PRECISION,
    spectral_contrast_std4 DOUBLE PRECISION,
    spectral_contrast_std5 DOUBLE PRECISION,
    spectral_contrast_std6 DOUBLE PRECISION,
    spectral_rolloff_kurtosis DOUBLE PRECISION,
    spectral_rolloff_max DOUBLE PRECISION,
    spectral_rolloff_mean DOUBLE PRECISION,
    spectral_rolloff_median DOUBLE PRECISION,
    spectral_rolloff_min DOUBLE PRECISION,
    spectral_rolloff_skew DOUBLE PRECISION,
    spectral_rolloff_std DOUBLE PRECISION,
    tonnetz_kurtosis DOUBLE PRECISION,
    tonnetz_kurtosis1 DOUBLE PRECISION,
    tonnetz_kurtosis2 DOUBLE PRECISION,
    tonnetz_kurtosis3 DOUBLE PRECISION,
    tonnetz_kurtosis4 DOUBLE PRECISION,
    tonnetz_kurtosis5 DOUBLE PRECISION,
    tonnetz_max DOUBLE PRECISION,
    tonnetz_max1 DOUBLE PRECISION,
    tonnetz_max2 DOUBLE PRECISION,
    tonnetz_max3 DOUBLE PRECISION,
    tonnetz_max4 DOUBLE PRECISION,
    tonnetz_max5 DOUBLE PRECISION,
    tonnetz_mean DOUBLE PRECISION,
    tonnetz_mean1 DOUBLE PRECISION,
    tonnetz_mean2 DOUBLE PRECISION,
    tonnetz_mean3 DOUBLE PRECISION,
    tonnetz_mean4 DOUBLE PRECISION,
    tonnetz_mean5 DOUBLE PRECISION,
    tonnetz_median DOUBLE PRECISION,
    tonnetz_median1 DOUBLE PRECISION,
    tonnetz_median2 DOUBLE PRECISION,
    tonnetz_median3 DOUBLE PRECISION,
    tonnetz_median4 DOUBLE PRECISION,
    tonnetz_median5 DOUBLE PRECISION,
    tonnetz_min DOUBLE PRECISION,
    tonnetz_min1 DOUBLE PRECISION,
    tonnetz_min2 DOUBLE PRECISION,
    tonnetz_min3 DOUBLE PRECISION,
    tonnetz_min4 DOUBLE PRECISION,
    tonnetz_min5 DOUBLE PRECISION,
    tonnetz_skew DOUBLE PRECISION,
    tonnetz_skew1 DOUBLE PRECISION,
    tonnetz_skew2 DOUBLE PRECISION,
    tonnetz_skew3 DOUBLE PRECISION,
    tonnetz_skew4 DOUBLE PRECISION,
    tonnetz_skew5 DOUBLE PRECISION,
    tonnetz_std DOUBLE PRECISION,
    tonnetz_std1 DOUBLE PRECISION,
    tonnetz_std2 DOUBLE PRECISION,
    tonnetz_std3 DOUBLE PRECISION,
    tonnetz_std4 DOUBLE PRECISION,
    tonnetz_std5 DOUBLE PRECISION,
    zcr_kurtosis DOUBLE PRECISION,
    zcr_max DOUBLE PRECISION,
    zcr_mean DOUBLE PRECISION,
    zcr_median DOUBLE PRECISION,
    zcr_min DOUBLE PRECISION,
    zcr_skew DOUBLE PRECISION,
    zcr_std DOUBLE PRECISION,
    PRIMARY KEY (track_id),
    FOREIGN KEY (track_id) REFERENCES track(track_id)
);

CREATE TABLE tag (
    tag_id UUID DEFAULT uuid_generate_v4(),
    tag_name VARCHAR(255),
    PRIMARY KEY (tag_id)
);

CREATE TABLE playlist (
    playlist_id UUID DEFAULT uuid_generate_v4(),
    playlist_name VARCHAR(255),
    PRIMARY KEY (playlist_id)
);

CREATE TABLE rank_track (
    track_id UUID,
    rank_song_currency BIGINT,
    rank_song_hotttnesss BIGINT,
    PRIMARY KEY (track_id),
    FOREIGN KEY (track_id) REFERENCES track(track_id)
);

CREATE TABLE rank_artist (
    artist_id UUID,
    rank_artist_discovery BIGINT,
    rank_artist_familiarity BIGINT,
    rank_artist_hotttnesss BIGINT,
    PRIMARY KEY (artist_id),
    FOREIGN KEY (artist_id) REFERENCES artist(artist_id)
);

CREATE TABLE license (
    license_id UUID DEFAULT uuid_generate_v4(),
    license_title VARCHAR(255),
    license_url VARCHAR(255),
    PRIMARY KEY (license_id)
);

CREATE TABLE track_genre (
    track_id UUID,
    genre_id UUID,
    PRIMARY KEY (track_id, genre_id),
    FOREIGN KEY (track_id) REFERENCES track(track_id),
    FOREIGN KEY (genre_id) REFERENCES genre(genre_id)
);

CREATE TABLE track_tag (
    track_id UUID,
    tag_id UUID,
    PRIMARY KEY (track_id, tag_id),
    FOREIGN KEY (track_id) REFERENCES track(track_id),
    FOREIGN KEY (tag_id) REFERENCES tag(tag_id)
);

CREATE TABLE artist_tag (
    artist_id UUID,
    tag_id UUID,
    PRIMARY KEY (artist_id, tag_id),
    FOREIGN KEY (artist_id) REFERENCES artist(artist_id),
    FOREIGN KEY (tag_id) REFERENCES tag(tag_id)
);

CREATE TABLE album_artist (
    album_id UUID,
    artist_id UUID,
    PRIMARY KEY (album_id, artist_id),
    FOREIGN KEY (album_id) REFERENCES album(album_id),
    FOREIGN KEY (artist_id) REFERENCES artist(artist_id)
);

CREATE TABLE track_artist_main (
    track_id UUID,
    artist_id UUID,
    PRIMARY KEY (track_id, artist_id),
    FOREIGN KEY (track_id) REFERENCES track(track_id),
    FOREIGN KEY (artist_id) REFERENCES artist(artist_id)
);

CREATE TABLE track_artist_feat (
    track_id UUID,
    artist_id UUID,
    PRIMARY KEY (track_id, artist_id),
    FOREIGN KEY (track_id) REFERENCES track(track_id),
    FOREIGN KEY (artist_id) REFERENCES artist(artist_id)
);

CREATE TABLE track_license (
    track_id UUID,
    license_id UUID,
    PRIMARY KEY (track_id, license_id),
    FOREIGN KEY (track_id) REFERENCES track(track_id),
    FOREIGN KEY (license_id) REFERENCES license(license_id)
);

CREATE TABLE playlist_track (
    playlist_id UUID,
    track_id UUID,
    PRIMARY KEY (playlist_id, track_id),
    FOREIGN KEY (playlist_id) REFERENCES playlist(playlist_id),
    FOREIGN KEY (track_id) REFERENCES track(track_id)
);

CREATE TABLE "user" (
    account_id UUID,
    pseudo VARCHAR(255),
    PRIMARY KEY (account_id),
    FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE TABLE preference (
    account_id UUID,
    age_range VARCHAR(255),
    gender VARCHAR(255),
    position VARCHAR(255),
    has_consented BOOLEAN,
    is_listening BOOLEAN,
    frequency VARCHAR(255),  -- CSV has text like "+ d'une fois par jour"
    when_listening DOUBLE PRECISION,
    duration_pref INTEGER,
    energy_pref VARCHAR(255),
    tempo_pref DOUBLE PRECISION,
    feeling_pref VARCHAR(255),
    is_live_pref VARCHAR(255),
    quality_pref INTEGER,
    curiosity_pref INTEGER,
    context VARCHAR(255),  -- CSV has list like "['seul(e)', 'entre amis']"
    how VARCHAR(255),
    platform VARCHAR(255),
    utility VARCHAR(255),
    track_genre VARCHAR(255),
    PRIMARY KEY (account_id),
    FOREIGN KEY (account_id) REFERENCES "user"(account_id)
);

CREATE TABLE playlist_user (
    playlist_id UUID,
    account_id UUID,
    PRIMARY KEY (playlist_id, account_id),
    FOREIGN KEY (playlist_id) REFERENCES playlist(playlist_id),
    FOREIGN KEY (account_id) REFERENCES "user"(account_id)
);

CREATE TABLE track_user_like (
    track_id UUID,
    account_id UUID,
    PRIMARY KEY (track_id, account_id),
    FOREIGN KEY (track_id) REFERENCES track(track_id),
    FOREIGN KEY (account_id) REFERENCES "user"(account_id)
);

CREATE TABLE track_user_listen (
    track_id UUID,
    account_id UUID,
    PRIMARY KEY (track_id, account_id),
    FOREIGN KEY (track_id) REFERENCES track(track_id),
    FOREIGN KEY (account_id) REFERENCES "user"(account_id)
);

