
SET synchronous_commit = off;
-- ====================================================================================
-- POPULATE SCRIPT
-- ====================================================================================

-- 1. Helper Functions
CREATE OR REPLACE FUNCTION parse_python_list(p_text TEXT) RETURNS TEXT[] AS $$
DECLARE
    clean_text TEXT;
BEGIN
    IF p_text IS NULL OR p_text = '' OR p_text = '[]' THEN
        RETURN ARRAY[]::TEXT[];
    END IF;
    
    clean_text := p_text;
    
    -- Handle double-escaped quotes often found in CSV dumps of python lists: ["\"val\""]
    IF position('""' IN clean_text) > 0 THEN
        clean_text := replace(clean_text, '""', '"');
    END IF;

    -- Replace Python-style single quotes with double quotes for JSON parsing
    -- Only if it starts with [ and '
    IF left(clean_text, 2) = '[''' THEN
         clean_text := replace(clean_text, '''', '"');
    END IF;
    
    -- Fallback for simple ' -> " replacement if not covered above but still looks like list
    IF left(clean_text, 1) = '[' AND position('''' IN clean_text) > 0 AND position('"' IN clean_text) = 0 THEN
         clean_text := replace(clean_text, '''', '"');
    END IF;

    -- If it looks like JSON now, try to parse
    BEGIN
        RETURN ARRAY(SELECT jsonb_array_elements_text(clean_text::jsonb));
    EXCEPTION WHEN OTHERS THEN
        -- Fallback: basic string splitting if JSON fails. 
        -- Removes brackets and quotes for simple CSV-like parsing
        RETURN string_to_array(replace(replace(replace(trim(both '[]' from p_text), '''', ''), '"', ''), ', ', ','), ',');
    END;
END;
$$ LANGUAGE plpgsql;

-- 2. Mapping Table for Legacy IDs
CREATE TEMP TABLE _legacy_id_map (
    table_name TEXT,
    old_id TEXT,
    new_uuid UUID
);
CREATE INDEX idx_legacy_map ON _legacy_id_map(table_name, old_id);

-- ====================================================================================
-- GENRE
-- ====================================================================================
CREATE TEMP TABLE stg_genre (
    genre_id TEXT,
    tracks_count INT,
    parent_id TEXT,
    title TEXT,
    top_level INT
);

\copy stg_genre FROM 'T1_analyse_de_donnees/cleaned_data/clean_genres.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');

-- Insert and Map
WITH inserted AS (
    INSERT INTO genre (title, top_level)
    SELECT title, top_level FROM stg_genre
    RETURNING genre_id, title
)
INSERT INTO _legacy_id_map (table_name, old_id, new_uuid)
SELECT 'genre', s.genre_id, i.genre_id
FROM stg_genre s
JOIN inserted i ON i.title = s.title; -- assuming title uniqueness for mapping or row order? 
-- Title might not be unique. Better approach: Use a DO block or function if title not unique. 
-- But strictly, we can't link back easily without a temporary key.
-- Since we are in a transaction, we can add a temp column to 'genre' or rely on order? No rely on order is risky.
-- Alternative: Generate UUIDs in staging first.

TRUNCATE TABLE _legacy_id_map; -- Start over with better approach

ALTER TABLE stg_genre ADD COLUMN new_uuid UUID DEFAULT uuid_generate_v4();

INSERT INTO genre (genre_id, title, top_level)
SELECT new_uuid, title, top_level FROM stg_genre;

INSERT INTO _legacy_id_map (table_name, old_id, new_uuid)
SELECT 'genre', genre_id, new_uuid FROM stg_genre;

-- Update Parent IDs
UPDATE genre g
SET parent_id = m_parent.new_uuid
FROM stg_genre s
JOIN _legacy_id_map m_self ON m_self.old_id = s.genre_id AND m_self.table_name = 'genre'
JOIN _legacy_id_map m_parent ON m_parent.old_id = s.parent_id AND m_parent.table_name = 'genre'
WHERE g.genre_id = m_self.new_uuid AND s.parent_id != '0' AND s.parent_id IS NOT NULL;


-- ====================================================================================
-- ARTIST
-- ====================================================================================
CREATE TEMP TABLE stg_artist (
    artist_id TEXT,
    artist_active_year_begin INT,
    artist_active_year_end INT,
    artist_associated_labels TEXT,
    artist_bio TEXT,
    artist_comments INT,
    artist_favorites INT,
    artist_latitude DOUBLE PRECISION,
    artist_location TEXT,
    artist_longitude DOUBLE PRECISION,
    artist_members TEXT,
    artist_name TEXT,
    artist_related_projects TEXT,
    tags TEXT
);

\copy stg_artist FROM 'T1_analyse_de_donnees/cleaned_data/clean_raw_artists.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');

ALTER TABLE stg_artist ADD COLUMN new_uuid UUID DEFAULT uuid_generate_v4();

-- Create Accounts for Artists
INSERT INTO account (account_id, login, name, email, created_at)
SELECT 
    new_uuid, 
    'artist_' || artist_id, 
    artist_name, 
    'artist_' || artist_id || '@example.com', 
    NOW()
FROM stg_artist;

-- Insert Artists
INSERT INTO artist (
    artist_id, artist_bio, artist_location, artist_latitude, artist_longitude, 
    artist_active_year_begin, artist_active_year_end, artist_favorites, artist_comments
)
SELECT 
    new_uuid, artist_bio, artist_location, artist_latitude, artist_longitude,
    artist_active_year_begin, artist_active_year_end, artist_favorites, artist_comments
FROM stg_artist;

INSERT INTO _legacy_id_map (table_name, old_id, new_uuid)
SELECT 'artist', artist_id, new_uuid FROM stg_artist;


-- ====================================================================================
-- ALBUM
-- ====================================================================================
CREATE TEMP TABLE stg_album (
    album_id TEXT,
    album_comments INT,
    album_date_released DATE,
    album_favorites INT,
    album_listens INT,
    album_producer TEXT,
    album_title TEXT,
    album_tracks INT,
    album_type TEXT,
    tags TEXT
);

\copy stg_album FROM 'T1_analyse_de_donnees/cleaned_data/clean_raw_albums.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');

ALTER TABLE stg_album ADD COLUMN new_uuid UUID DEFAULT uuid_generate_v4();

INSERT INTO album (
    album_id, album_title, album_type, album_tracks_count, album_date_released, 
    album_listens, album_favorites, album_comments, album_producer
)
SELECT 
    new_uuid, album_title, album_type, album_tracks, album_date_released,
    album_listens, album_favorites, album_comments, album_producer
FROM stg_album;

INSERT INTO _legacy_id_map (table_name, old_id, new_uuid)
SELECT 'album', album_id, new_uuid FROM stg_album;


-- ====================================================================================
-- TRACK
-- ====================================================================================
CREATE TEMP TABLE stg_track (
    track_id TEXT,
    album_id TEXT,
    artist_id TEXT,
    track_comments INT,
    track_composer TEXT,
    track_date_created DATE,
    track_duration INT,
    track_favorites INT,
    track_genre_top TEXT,
    track_genres TEXT,
    track_interest DOUBLE PRECISION,
    track_listens INT,
    track_lyricist TEXT,
    track_publisher TEXT,
    track_tags TEXT,
    track_title TEXT
);

\copy stg_track FROM 'T1_analyse_de_donnees/cleaned_data/clean_tracks.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');

ALTER TABLE stg_track ADD COLUMN new_uuid UUID DEFAULT uuid_generate_v4();

INSERT INTO track (
    track_id, album_id, track_title, track_duration, track_listens, 
    track_favorites, track_interest, track_comments, track_date_created, 
    track_composer, track_lyricist, track_publisher
)
SELECT 
    t.new_uuid, 
    m_alb.new_uuid, 
    t.track_title, 
    t.track_duration, 
    t.track_listens, 
    t.track_favorites, 
    t.track_interest, 
    t.track_comments, 
    t.track_date_created, 
    t.track_composer, 
    t.track_lyricist, 
    t.track_publisher
FROM stg_track t
LEFT JOIN _legacy_id_map m_alb ON m_alb.old_id = t.album_id AND m_alb.table_name = 'album'
JOIN _legacy_id_map m_art ON m_art.old_id = t.artist_id AND m_art.table_name = 'artist';

INSERT INTO _legacy_id_map (table_name, old_id, new_uuid)
SELECT 'track', t.track_id, t.new_uuid 
FROM stg_track t
JOIN _legacy_id_map m_art ON m_art.old_id = t.artist_id AND m_art.table_name = 'artist';

-- Link Track -> Artist (Main)
INSERT INTO track_artist_main (track_id, artist_id)
SELECT 
    t.new_uuid, 
    m_art.new_uuid
FROM stg_track t
JOIN _legacy_id_map m_art ON m_art.old_id = t.artist_id AND m_art.table_name = 'artist';

-- Link Album -> Artist (Derived from Tracks)
INSERT INTO album_artist (album_id, artist_id)
SELECT DISTINCT 
    m_alb.new_uuid, 
    m_art.new_uuid
FROM stg_track t
JOIN _legacy_id_map m_alb ON m_alb.old_id = t.album_id AND m_alb.table_name = 'album'
JOIN _legacy_id_map m_art ON m_art.old_id = t.artist_id AND m_art.table_name = 'artist'
ON CONFLICT DO NOTHING;

-- Link Track -> Genres (List parsing)
-- track_genres is like '[21, 3]'
WITH exploded AS (
    SELECT 
        new_uuid as track_uuid, 
        trim(genre_old_id) as genre_old_id
    FROM stg_track, unnest(parse_python_list(track_genres)) as genre_old_id
    WHERE track_genres IS NOT NULL AND track_genres != '[]'
),
cleaned_ids AS (
    SELECT track_uuid, genre_old_id
    FROM exploded
)
INSERT INTO track_genre (track_id, genre_id)
SELECT 
    c.track_uuid, 
    m.new_uuid
FROM cleaned_ids c
JOIN _legacy_id_map m ON m.old_id = c.genre_old_id AND m.table_name = 'genre' JOIN track t ON t.track_id = c.track_uuid
ON CONFLICT DO NOTHING;


-- ====================================================================================
-- TAGS (from Artists and Tracks)
-- ====================================================================================
CREATE TEMP TABLE stg_tags (
    tag_name TEXT
);

-- Extract from Artists
INSERT INTO stg_tags (tag_name)
SELECT DISTINCT trim(elem)
FROM stg_artist, unnest(parse_python_list(tags)) as elem;

-- Extract from Tracks
INSERT INTO stg_tags (tag_name)
SELECT DISTINCT trim(elem)
FROM stg_track, unnest(parse_python_list(track_tags)) as elem;

-- Insert Tags
INSERT INTO tag (tag_name)
SELECT DISTINCT tag_name FROM stg_tags WHERE tag_name IS NOT NULL AND tag_name != ''
ON CONFLICT DO NOTHING;

-- Link Artist Tags
INSERT INTO artist_tag (artist_id, tag_id)
SELECT DISTINCT a.new_uuid, tg.tag_id
FROM stg_artist a, unnest(parse_python_list(a.tags)) as tname
JOIN tag tg ON tg.tag_name = trim(tname)
ON CONFLICT DO NOTHING;

-- Link Track Tags
INSERT INTO track_tag (track_id, tag_id)
SELECT DISTINCT t.new_uuid, tg.tag_id
FROM stg_track t
CROSS JOIN LATERAL unnest(parse_python_list(t.track_tags)) as tname
JOIN tag tg ON tg.tag_name = trim(tname) 
JOIN track tr ON tr.track_id = t.new_uuid
ON CONFLICT DO NOTHING;


-- ====================================================================================
-- AUDIO FEATURES & RANKS (clean_echonest.csv)
-- ====================================================================================
CREATE TEMP TABLE stg_echonest (
    track_id TEXT,
    acousticness DOUBLE PRECISION,
    danceability DOUBLE PRECISION,
    energy DOUBLE PRECISION,
    instrumentalness DOUBLE PRECISION,
    liveness DOUBLE PRECISION,
    speechiness DOUBLE PRECISION,
    tempo DOUBLE PRECISION,
    valence DOUBLE PRECISION,
    artist_discovery_rank DOUBLE PRECISION,
    artist_familiarity_rank DOUBLE PRECISION,
    artist_hotttnesss_rank DOUBLE PRECISION,
    song_currency_rank DOUBLE PRECISION,
    song_hotttnesss_rank DOUBLE PRECISION,
    artist_discovery DOUBLE PRECISION,
    artist_familiarity DOUBLE PRECISION,
    artist_hotttnesss DOUBLE PRECISION,
    song_currency DOUBLE PRECISION,
    song_hotttnesss DOUBLE PRECISION
);

\copy stg_echonest FROM 'T1_analyse_de_donnees/cleaned_data/clean_echonest.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');

-- Insert Audio Features
INSERT INTO audio_feature (
    track_id, acousticness, danceability, energy, instrumentalness, 
    liveness, speechiness, tempo, valence
)
SELECT 
    m.new_uuid, s.acousticness, s.danceability, s.energy, s.instrumentalness,
    s.liveness, s.speechiness, s.tempo, s.valence
FROM stg_echonest s
JOIN _legacy_id_map m ON m.old_id = s.track_id AND m.table_name = 'track'
ON CONFLICT (track_id) DO UPDATE SET 
    acousticness = EXCLUDED.acousticness,
    danceability = EXCLUDED.danceability,
    energy = EXCLUDED.energy;

-- Update Ranks (using the ranks logic)
-- rank_track
INSERT INTO rank_track (track_id, rank_song_currency, rank_song_hotttnesss)
SELECT 
    m.new_uuid, 
    CAST(s.song_currency_rank AS BIGINT), 
    CAST(s.song_hotttnesss_rank AS BIGINT)
FROM stg_echonest s
JOIN _legacy_id_map m ON m.old_id = s.track_id AND m.table_name = 'track'
ON CONFLICT DO NOTHING; -- or update if exists, logic allows multiple dates now

-- rank_artist (derived from echonest, associated with track's artist)
-- Need to find artist for the track
INSERT INTO rank_artist (artist_id, rank_artist_discovery, rank_artist_familiarity, rank_artist_hotttnesss)
SELECT DISTINCT
    ta.artist_id,
    CAST(s.artist_discovery_rank AS BIGINT),
    CAST(s.artist_familiarity_rank AS BIGINT),
    CAST(s.artist_hotttnesss_rank AS BIGINT)
FROM stg_echonest s
JOIN _legacy_id_map m ON m.old_id = s.track_id AND m.table_name = 'track'
JOIN track_artist_main ta ON ta.track_id = m.new_uuid
WHERE s.artist_discovery_rank IS NOT NULL
ON CONFLICT DO NOTHING;


-- ====================================================================================
-- TEMPORAL FEATURES (clean_features.csv)
-- ====================================================================================
CREATE TEMP TABLE stg_features (
    track_id TEXT,
    chroma_cens_kurtosis DOUBLE PRECISION,
    "chroma_cens_kurtosis.1" DOUBLE PRECISION,
    "chroma_cens_kurtosis.2" DOUBLE PRECISION,
    "chroma_cens_kurtosis.3" DOUBLE PRECISION,
    "chroma_cens_kurtosis.4" DOUBLE PRECISION,
    "chroma_cens_kurtosis.5" DOUBLE PRECISION,
    "chroma_cens_kurtosis.6" DOUBLE PRECISION,
    "chroma_cens_kurtosis.7" DOUBLE PRECISION,
    "chroma_cens_kurtosis.8" DOUBLE PRECISION,
    "chroma_cens_kurtosis.9" DOUBLE PRECISION,
    "chroma_cens_kurtosis.10" DOUBLE PRECISION,
    "chroma_cens_kurtosis.11" DOUBLE PRECISION,
    chroma_cens_max DOUBLE PRECISION,
    "chroma_cens_max.1" DOUBLE PRECISION,
    "chroma_cens_max.2" DOUBLE PRECISION,
    "chroma_cens_max.3" DOUBLE PRECISION,
    "chroma_cens_max.4" DOUBLE PRECISION,
    "chroma_cens_max.5" DOUBLE PRECISION,
    "chroma_cens_max.6" DOUBLE PRECISION,
    "chroma_cens_max.7" DOUBLE PRECISION,
    "chroma_cens_max.8" DOUBLE PRECISION,
    "chroma_cens_max.9" DOUBLE PRECISION,
    "chroma_cens_max.10" DOUBLE PRECISION,
    "chroma_cens_max.11" DOUBLE PRECISION,
    chroma_cens_mean DOUBLE PRECISION,
    "chroma_cens_mean.1" DOUBLE PRECISION,
    "chroma_cens_mean.2" DOUBLE PRECISION,
    "chroma_cens_mean.3" DOUBLE PRECISION,
    "chroma_cens_mean.4" DOUBLE PRECISION,
    "chroma_cens_mean.5" DOUBLE PRECISION,
    "chroma_cens_mean.6" DOUBLE PRECISION,
    "chroma_cens_mean.7" DOUBLE PRECISION,
    "chroma_cens_mean.8" DOUBLE PRECISION,
    "chroma_cens_mean.9" DOUBLE PRECISION,
    "chroma_cens_mean.10" DOUBLE PRECISION,
    "chroma_cens_mean.11" DOUBLE PRECISION,
    chroma_cens_median DOUBLE PRECISION,
    "chroma_cens_median.1" DOUBLE PRECISION,
    "chroma_cens_median.2" DOUBLE PRECISION,
    "chroma_cens_median.3" DOUBLE PRECISION,
    "chroma_cens_median.4" DOUBLE PRECISION,
    "chroma_cens_median.5" DOUBLE PRECISION,
    "chroma_cens_median.6" DOUBLE PRECISION,
    "chroma_cens_median.7" DOUBLE PRECISION,
    "chroma_cens_median.8" DOUBLE PRECISION,
    "chroma_cens_median.9" DOUBLE PRECISION,
    "chroma_cens_median.10" DOUBLE PRECISION,
    "chroma_cens_median.11" DOUBLE PRECISION,
    chroma_cens_min DOUBLE PRECISION,
    "chroma_cens_min.1" DOUBLE PRECISION,
    "chroma_cens_min.2" DOUBLE PRECISION,
    "chroma_cens_min.3" DOUBLE PRECISION,
    "chroma_cens_min.4" DOUBLE PRECISION,
    "chroma_cens_min.5" DOUBLE PRECISION,
    "chroma_cens_min.6" DOUBLE PRECISION,
    "chroma_cens_min.7" DOUBLE PRECISION,
    "chroma_cens_min.8" DOUBLE PRECISION,
    "chroma_cens_min.9" DOUBLE PRECISION,
    "chroma_cens_min.10" DOUBLE PRECISION,
    "chroma_cens_min.11" DOUBLE PRECISION,
    chroma_cens_skew DOUBLE PRECISION,
    "chroma_cens_skew.1" DOUBLE PRECISION,
    "chroma_cens_skew.2" DOUBLE PRECISION,
    "chroma_cens_skew.3" DOUBLE PRECISION,
    "chroma_cens_skew.4" DOUBLE PRECISION,
    "chroma_cens_skew.5" DOUBLE PRECISION,
    "chroma_cens_skew.6" DOUBLE PRECISION,
    "chroma_cens_skew.7" DOUBLE PRECISION,
    "chroma_cens_skew.8" DOUBLE PRECISION,
    "chroma_cens_skew.9" DOUBLE PRECISION,
    "chroma_cens_skew.10" DOUBLE PRECISION,
    "chroma_cens_skew.11" DOUBLE PRECISION,
    chroma_cens_std DOUBLE PRECISION,
    "chroma_cens_std.1" DOUBLE PRECISION,
    "chroma_cens_std.2" DOUBLE PRECISION,
    "chroma_cens_std.3" DOUBLE PRECISION,
    "chroma_cens_std.4" DOUBLE PRECISION,
    "chroma_cens_std.5" DOUBLE PRECISION,
    "chroma_cens_std.6" DOUBLE PRECISION,
    "chroma_cens_std.7" DOUBLE PRECISION,
    "chroma_cens_std.8" DOUBLE PRECISION,
    "chroma_cens_std.9" DOUBLE PRECISION,
    "chroma_cens_std.10" DOUBLE PRECISION,
    "chroma_cens_std.11" DOUBLE PRECISION,
    chroma_cqt_kurtosis DOUBLE PRECISION,
    "chroma_cqt_kurtosis.1" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.2" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.3" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.4" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.5" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.6" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.7" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.8" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.9" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.10" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.11" DOUBLE PRECISION,
    chroma_cqt_max DOUBLE PRECISION,
    "chroma_cqt_max.1" DOUBLE PRECISION,
    "chroma_cqt_max.2" DOUBLE PRECISION,
    "chroma_cqt_max.3" DOUBLE PRECISION,
    "chroma_cqt_max.4" DOUBLE PRECISION,
    "chroma_cqt_max.5" DOUBLE PRECISION,
    "chroma_cqt_max.6" DOUBLE PRECISION,
    "chroma_cqt_max.7" DOUBLE PRECISION,
    "chroma_cqt_max.8" DOUBLE PRECISION,
    "chroma_cqt_max.9" DOUBLE PRECISION,
    "chroma_cqt_max.10" DOUBLE PRECISION,
    "chroma_cqt_max.11" DOUBLE PRECISION,
    chroma_cqt_mean DOUBLE PRECISION,
    "chroma_cqt_mean.1" DOUBLE PRECISION,
    "chroma_cqt_mean.2" DOUBLE PRECISION,
    "chroma_cqt_mean.3" DOUBLE PRECISION,
    "chroma_cqt_mean.4" DOUBLE PRECISION,
    "chroma_cqt_mean.5" DOUBLE PRECISION,
    "chroma_cqt_mean.6" DOUBLE PRECISION,
    "chroma_cqt_mean.7" DOUBLE PRECISION,
    "chroma_cqt_mean.8" DOUBLE PRECISION,
    "chroma_cqt_mean.9" DOUBLE PRECISION,
    "chroma_cqt_mean.10" DOUBLE PRECISION,
    "chroma_cqt_mean.11" DOUBLE PRECISION,
    chroma_cqt_median DOUBLE PRECISION,
    "chroma_cqt_median.1" DOUBLE PRECISION,
    "chroma_cqt_median.2" DOUBLE PRECISION,
    "chroma_cqt_median.3" DOUBLE PRECISION,
    "chroma_cqt_median.4" DOUBLE PRECISION,
    "chroma_cqt_median.5" DOUBLE PRECISION,
    "chroma_cqt_median.6" DOUBLE PRECISION,
    "chroma_cqt_median.7" DOUBLE PRECISION,
    "chroma_cqt_median.8" DOUBLE PRECISION,
    "chroma_cqt_median.9" DOUBLE PRECISION,
    "chroma_cqt_median.10" DOUBLE PRECISION,
    "chroma_cqt_median.11" DOUBLE PRECISION,
    chroma_cqt_min DOUBLE PRECISION,
    "chroma_cqt_min.1" DOUBLE PRECISION,
    "chroma_cqt_min.2" DOUBLE PRECISION,
    "chroma_cqt_min.3" DOUBLE PRECISION,
    "chroma_cqt_min.4" DOUBLE PRECISION,
    "chroma_cqt_min.5" DOUBLE PRECISION,
    "chroma_cqt_min.6" DOUBLE PRECISION,
    "chroma_cqt_min.7" DOUBLE PRECISION,
    "chroma_cqt_min.8" DOUBLE PRECISION,
    "chroma_cqt_min.9" DOUBLE PRECISION,
    "chroma_cqt_min.10" DOUBLE PRECISION,
    "chroma_cqt_min.11" DOUBLE PRECISION,
    chroma_cqt_skew DOUBLE PRECISION,
    "chroma_cqt_skew.1" DOUBLE PRECISION,
    "chroma_cqt_skew.2" DOUBLE PRECISION,
    "chroma_cqt_skew.3" DOUBLE PRECISION,
    "chroma_cqt_skew.4" DOUBLE PRECISION,
    "chroma_cqt_skew.5" DOUBLE PRECISION,
    "chroma_cqt_skew.6" DOUBLE PRECISION,
    "chroma_cqt_skew.7" DOUBLE PRECISION,
    "chroma_cqt_skew.8" DOUBLE PRECISION,
    "chroma_cqt_skew.9" DOUBLE PRECISION,
    "chroma_cqt_skew.10" DOUBLE PRECISION,
    "chroma_cqt_skew.11" DOUBLE PRECISION,
    chroma_cqt_std DOUBLE PRECISION,
    "chroma_cqt_std.1" DOUBLE PRECISION,
    "chroma_cqt_std.2" DOUBLE PRECISION,
    "chroma_cqt_std.3" DOUBLE PRECISION,
    "chroma_cqt_std.4" DOUBLE PRECISION,
    "chroma_cqt_std.5" DOUBLE PRECISION,
    "chroma_cqt_std.6" DOUBLE PRECISION,
    "chroma_cqt_std.7" DOUBLE PRECISION,
    "chroma_cqt_std.8" DOUBLE PRECISION,
    "chroma_cqt_std.9" DOUBLE PRECISION,
    "chroma_cqt_std.10" DOUBLE PRECISION,
    "chroma_cqt_std.11" DOUBLE PRECISION,
    chroma_stft_kurtosis DOUBLE PRECISION,
    "chroma_stft_kurtosis.1" DOUBLE PRECISION,
    "chroma_stft_kurtosis.2" DOUBLE PRECISION,
    "chroma_stft_kurtosis.3" DOUBLE PRECISION,
    "chroma_stft_kurtosis.4" DOUBLE PRECISION,
    "chroma_stft_kurtosis.5" DOUBLE PRECISION,
    "chroma_stft_kurtosis.6" DOUBLE PRECISION,
    "chroma_stft_kurtosis.7" DOUBLE PRECISION,
    "chroma_stft_kurtosis.8" DOUBLE PRECISION,
    "chroma_stft_kurtosis.9" DOUBLE PRECISION,
    "chroma_stft_kurtosis.10" DOUBLE PRECISION,
    "chroma_stft_kurtosis.11" DOUBLE PRECISION,
    chroma_stft_max DOUBLE PRECISION,
    "chroma_stft_max.1" DOUBLE PRECISION,
    "chroma_stft_max.2" DOUBLE PRECISION,
    "chroma_stft_max.3" DOUBLE PRECISION,
    "chroma_stft_max.4" DOUBLE PRECISION,
    "chroma_stft_max.5" DOUBLE PRECISION,
    "chroma_stft_max.6" DOUBLE PRECISION,
    "chroma_stft_max.7" DOUBLE PRECISION,
    "chroma_stft_max.8" DOUBLE PRECISION,
    "chroma_stft_max.9" DOUBLE PRECISION,
    "chroma_stft_max.10" DOUBLE PRECISION,
    "chroma_stft_max.11" DOUBLE PRECISION,
    chroma_stft_mean DOUBLE PRECISION,
    "chroma_stft_mean.1" DOUBLE PRECISION,
    "chroma_stft_mean.2" DOUBLE PRECISION,
    "chroma_stft_mean.3" DOUBLE PRECISION,
    "chroma_stft_mean.4" DOUBLE PRECISION,
    "chroma_stft_mean.5" DOUBLE PRECISION,
    "chroma_stft_mean.6" DOUBLE PRECISION,
    "chroma_stft_mean.7" DOUBLE PRECISION,
    "chroma_stft_mean.8" DOUBLE PRECISION,
    "chroma_stft_mean.9" DOUBLE PRECISION,
    "chroma_stft_mean.10" DOUBLE PRECISION,
    "chroma_stft_mean.11" DOUBLE PRECISION,
    chroma_stft_median DOUBLE PRECISION,
    "chroma_stft_median.1" DOUBLE PRECISION,
    "chroma_stft_median.2" DOUBLE PRECISION,
    "chroma_stft_median.3" DOUBLE PRECISION,
    "chroma_stft_median.4" DOUBLE PRECISION,
    "chroma_stft_median.5" DOUBLE PRECISION,
    "chroma_stft_median.6" DOUBLE PRECISION,
    "chroma_stft_median.7" DOUBLE PRECISION,
    "chroma_stft_median.8" DOUBLE PRECISION,
    "chroma_stft_median.9" DOUBLE PRECISION,
    "chroma_stft_median.10" DOUBLE PRECISION,
    "chroma_stft_median.11" DOUBLE PRECISION,
    chroma_stft_min DOUBLE PRECISION,
    "chroma_stft_min.1" DOUBLE PRECISION,
    "chroma_stft_min.2" DOUBLE PRECISION,
    "chroma_stft_min.3" DOUBLE PRECISION,
    "chroma_stft_min.4" DOUBLE PRECISION,
    "chroma_stft_min.5" DOUBLE PRECISION,
    "chroma_stft_min.6" DOUBLE PRECISION,
    "chroma_stft_min.7" DOUBLE PRECISION,
    "chroma_stft_min.8" DOUBLE PRECISION,
    "chroma_stft_min.9" DOUBLE PRECISION,
    "chroma_stft_min.10" DOUBLE PRECISION,
    "chroma_stft_min.11" DOUBLE PRECISION,
    chroma_stft_skew DOUBLE PRECISION,
    "chroma_stft_skew.1" DOUBLE PRECISION,
    "chroma_stft_skew.2" DOUBLE PRECISION,
    "chroma_stft_skew.3" DOUBLE PRECISION,
    "chroma_stft_skew.4" DOUBLE PRECISION,
    "chroma_stft_skew.5" DOUBLE PRECISION,
    "chroma_stft_skew.6" DOUBLE PRECISION,
    "chroma_stft_skew.7" DOUBLE PRECISION,
    "chroma_stft_skew.8" DOUBLE PRECISION,
    "chroma_stft_skew.9" DOUBLE PRECISION,
    "chroma_stft_skew.10" DOUBLE PRECISION,
    "chroma_stft_skew.11" DOUBLE PRECISION,
    chroma_stft_std DOUBLE PRECISION,
    "chroma_stft_std.1" DOUBLE PRECISION,
    "chroma_stft_std.2" DOUBLE PRECISION,
    "chroma_stft_std.3" DOUBLE PRECISION,
    "chroma_stft_std.4" DOUBLE PRECISION,
    "chroma_stft_std.5" DOUBLE PRECISION,
    "chroma_stft_std.6" DOUBLE PRECISION,
    "chroma_stft_std.7" DOUBLE PRECISION,
    "chroma_stft_std.8" DOUBLE PRECISION,
    "chroma_stft_std.9" DOUBLE PRECISION,
    "chroma_stft_std.10" DOUBLE PRECISION,
    "chroma_stft_std.11" DOUBLE PRECISION,
    mfcc_kurtosis DOUBLE PRECISION,
    "mfcc_kurtosis.1" DOUBLE PRECISION,
    "mfcc_kurtosis.2" DOUBLE PRECISION,
    "mfcc_kurtosis.3" DOUBLE PRECISION,
    "mfcc_kurtosis.4" DOUBLE PRECISION,
    "mfcc_kurtosis.5" DOUBLE PRECISION,
    "mfcc_kurtosis.6" DOUBLE PRECISION,
    "mfcc_kurtosis.7" DOUBLE PRECISION,
    "mfcc_kurtosis.8" DOUBLE PRECISION,
    "mfcc_kurtosis.9" DOUBLE PRECISION,
    "mfcc_kurtosis.10" DOUBLE PRECISION,
    "mfcc_kurtosis.11" DOUBLE PRECISION,
    "mfcc_kurtosis.12" DOUBLE PRECISION,
    "mfcc_kurtosis.13" DOUBLE PRECISION,
    "mfcc_kurtosis.14" DOUBLE PRECISION,
    "mfcc_kurtosis.15" DOUBLE PRECISION,
    "mfcc_kurtosis.16" DOUBLE PRECISION,
    "mfcc_kurtosis.17" DOUBLE PRECISION,
    "mfcc_kurtosis.18" DOUBLE PRECISION,
    "mfcc_kurtosis.19" DOUBLE PRECISION,
    mfcc_max DOUBLE PRECISION,
    "mfcc_max.1" DOUBLE PRECISION,
    "mfcc_max.2" DOUBLE PRECISION,
    "mfcc_max.3" DOUBLE PRECISION,
    "mfcc_max.4" DOUBLE PRECISION,
    "mfcc_max.5" DOUBLE PRECISION,
    "mfcc_max.6" DOUBLE PRECISION,
    "mfcc_max.7" DOUBLE PRECISION,
    "mfcc_max.8" DOUBLE PRECISION,
    "mfcc_max.9" DOUBLE PRECISION,
    "mfcc_max.10" DOUBLE PRECISION,
    "mfcc_max.11" DOUBLE PRECISION,
    "mfcc_max.12" DOUBLE PRECISION,
    "mfcc_max.13" DOUBLE PRECISION,
    "mfcc_max.14" DOUBLE PRECISION,
    "mfcc_max.15" DOUBLE PRECISION,
    "mfcc_max.16" DOUBLE PRECISION,
    "mfcc_max.17" DOUBLE PRECISION,
    "mfcc_max.18" DOUBLE PRECISION,
    "mfcc_max.19" DOUBLE PRECISION,
    mfcc_mean DOUBLE PRECISION,
    "mfcc_mean.1" DOUBLE PRECISION,
    "mfcc_mean.2" DOUBLE PRECISION,
    "mfcc_mean.3" DOUBLE PRECISION,
    "mfcc_mean.4" DOUBLE PRECISION,
    "mfcc_mean.5" DOUBLE PRECISION,
    "mfcc_mean.6" DOUBLE PRECISION,
    "mfcc_mean.7" DOUBLE PRECISION,
    "mfcc_mean.8" DOUBLE PRECISION,
    "mfcc_mean.9" DOUBLE PRECISION,
    "mfcc_mean.10" DOUBLE PRECISION,
    "mfcc_mean.11" DOUBLE PRECISION,
    "mfcc_mean.12" DOUBLE PRECISION,
    "mfcc_mean.13" DOUBLE PRECISION,
    "mfcc_mean.14" DOUBLE PRECISION,
    "mfcc_mean.15" DOUBLE PRECISION,
    "mfcc_mean.16" DOUBLE PRECISION,
    "mfcc_mean.17" DOUBLE PRECISION,
    "mfcc_mean.18" DOUBLE PRECISION,
    "mfcc_mean.19" DOUBLE PRECISION,
    mfcc_median DOUBLE PRECISION,
    "mfcc_median.1" DOUBLE PRECISION,
    "mfcc_median.2" DOUBLE PRECISION,
    "mfcc_median.3" DOUBLE PRECISION,
    "mfcc_median.4" DOUBLE PRECISION,
    "mfcc_median.5" DOUBLE PRECISION,
    "mfcc_median.6" DOUBLE PRECISION,
    "mfcc_median.7" DOUBLE PRECISION,
    "mfcc_median.8" DOUBLE PRECISION,
    "mfcc_median.9" DOUBLE PRECISION,
    "mfcc_median.10" DOUBLE PRECISION,
    "mfcc_median.11" DOUBLE PRECISION,
    "mfcc_median.12" DOUBLE PRECISION,
    "mfcc_median.13" DOUBLE PRECISION,
    "mfcc_median.14" DOUBLE PRECISION,
    "mfcc_median.15" DOUBLE PRECISION,
    "mfcc_median.16" DOUBLE PRECISION,
    "mfcc_median.17" DOUBLE PRECISION,
    "mfcc_median.18" DOUBLE PRECISION,
    "mfcc_median.19" DOUBLE PRECISION,
    mfcc_min DOUBLE PRECISION,
    "mfcc_min.1" DOUBLE PRECISION,
    "mfcc_min.2" DOUBLE PRECISION,
    "mfcc_min.3" DOUBLE PRECISION,
    "mfcc_min.4" DOUBLE PRECISION,
    "mfcc_min.5" DOUBLE PRECISION,
    "mfcc_min.6" DOUBLE PRECISION,
    "mfcc_min.7" DOUBLE PRECISION,
    "mfcc_min.8" DOUBLE PRECISION,
    "mfcc_min.9" DOUBLE PRECISION,
    "mfcc_min.10" DOUBLE PRECISION,
    "mfcc_min.11" DOUBLE PRECISION,
    "mfcc_min.12" DOUBLE PRECISION,
    "mfcc_min.13" DOUBLE PRECISION,
    "mfcc_min.14" DOUBLE PRECISION,
    "mfcc_min.15" DOUBLE PRECISION,
    "mfcc_min.16" DOUBLE PRECISION,
    "mfcc_min.17" DOUBLE PRECISION,
    "mfcc_min.18" DOUBLE PRECISION,
    "mfcc_min.19" DOUBLE PRECISION,
    mfcc_skew DOUBLE PRECISION,
    "mfcc_skew.1" DOUBLE PRECISION,
    "mfcc_skew.2" DOUBLE PRECISION,
    "mfcc_skew.3" DOUBLE PRECISION,
    "mfcc_skew.4" DOUBLE PRECISION,
    "mfcc_skew.5" DOUBLE PRECISION,
    "mfcc_skew.6" DOUBLE PRECISION,
    "mfcc_skew.7" DOUBLE PRECISION,
    "mfcc_skew.8" DOUBLE PRECISION,
    "mfcc_skew.9" DOUBLE PRECISION,
    "mfcc_skew.10" DOUBLE PRECISION,
    "mfcc_skew.11" DOUBLE PRECISION,
    "mfcc_skew.12" DOUBLE PRECISION,
    "mfcc_skew.13" DOUBLE PRECISION,
    "mfcc_skew.14" DOUBLE PRECISION,
    "mfcc_skew.15" DOUBLE PRECISION,
    "mfcc_skew.16" DOUBLE PRECISION,
    "mfcc_skew.17" DOUBLE PRECISION,
    "mfcc_skew.18" DOUBLE PRECISION,
    "mfcc_skew.19" DOUBLE PRECISION,
    mfcc_std DOUBLE PRECISION,
    "mfcc_std.1" DOUBLE PRECISION,
    "mfcc_std.2" DOUBLE PRECISION,
    "mfcc_std.3" DOUBLE PRECISION,
    "mfcc_std.4" DOUBLE PRECISION,
    "mfcc_std.5" DOUBLE PRECISION,
    "mfcc_std.6" DOUBLE PRECISION,
    "mfcc_std.7" DOUBLE PRECISION,
    "mfcc_std.8" DOUBLE PRECISION,
    "mfcc_std.9" DOUBLE PRECISION,
    "mfcc_std.10" DOUBLE PRECISION,
    "mfcc_std.11" DOUBLE PRECISION,
    "mfcc_std.12" DOUBLE PRECISION,
    "mfcc_std.13" DOUBLE PRECISION,
    "mfcc_std.14" DOUBLE PRECISION,
    "mfcc_std.15" DOUBLE PRECISION,
    "mfcc_std.16" DOUBLE PRECISION,
    "mfcc_std.17" DOUBLE PRECISION,
    "mfcc_std.18" DOUBLE PRECISION,
    "mfcc_std.19" DOUBLE PRECISION,
    rmse_kurtosis DOUBLE PRECISION,
    rmse_max DOUBLE PRECISION,
    rmse_mean DOUBLE PRECISION,
    rmse_median DOUBLE PRECISION,
    rmse_min DOUBLE PRECISION,
    rmse_skew DOUBLE PRECISION,
    rmse_std DOUBLE PRECISION,
    spectral_bandwidth_kurtosis DOUBLE PRECISION,
    spectral_bandwidth_max DOUBLE PRECISION,
    spectral_bandwidth_mean DOUBLE PRECISION,
    spectral_bandwidth_median DOUBLE PRECISION,
    spectral_bandwidth_min DOUBLE PRECISION,
    spectral_bandwidth_skew DOUBLE PRECISION,
    spectral_bandwidth_std DOUBLE PRECISION,
    spectral_centroid_kurtosis DOUBLE PRECISION,
    spectral_centroid_max DOUBLE PRECISION,
    spectral_centroid_mean DOUBLE PRECISION,
    spectral_centroid_median DOUBLE PRECISION,
    spectral_centroid_min DOUBLE PRECISION,
    spectral_centroid_skew DOUBLE PRECISION,
    spectral_centroid_std DOUBLE PRECISION,
    spectral_contrast_kurtosis DOUBLE PRECISION,
    "spectral_contrast_kurtosis.1" DOUBLE PRECISION,
    "spectral_contrast_kurtosis.2" DOUBLE PRECISION,
    "spectral_contrast_kurtosis.3" DOUBLE PRECISION,
    "spectral_contrast_kurtosis.4" DOUBLE PRECISION,
    "spectral_contrast_kurtosis.5" DOUBLE PRECISION,
    "spectral_contrast_kurtosis.6" DOUBLE PRECISION,
    spectral_contrast_max DOUBLE PRECISION,
    "spectral_contrast_max.1" DOUBLE PRECISION,
    "spectral_contrast_max.2" DOUBLE PRECISION,
    "spectral_contrast_max.3" DOUBLE PRECISION,
    "spectral_contrast_max.4" DOUBLE PRECISION,
    "spectral_contrast_max.5" DOUBLE PRECISION,
    "spectral_contrast_max.6" DOUBLE PRECISION,
    spectral_contrast_mean DOUBLE PRECISION,
    "spectral_contrast_mean.1" DOUBLE PRECISION,
    "spectral_contrast_mean.2" DOUBLE PRECISION,
    "spectral_contrast_mean.3" DOUBLE PRECISION,
    "spectral_contrast_mean.4" DOUBLE PRECISION,
    "spectral_contrast_mean.5" DOUBLE PRECISION,
    "spectral_contrast_mean.6" DOUBLE PRECISION,
    spectral_contrast_median DOUBLE PRECISION,
    "spectral_contrast_median.1" DOUBLE PRECISION,
    "spectral_contrast_median.2" DOUBLE PRECISION,
    "spectral_contrast_median.3" DOUBLE PRECISION,
    "spectral_contrast_median.4" DOUBLE PRECISION,
    "spectral_contrast_median.5" DOUBLE PRECISION,
    "spectral_contrast_median.6" DOUBLE PRECISION,
    spectral_contrast_min DOUBLE PRECISION,
    "spectral_contrast_min.1" DOUBLE PRECISION,
    "spectral_contrast_min.2" DOUBLE PRECISION,
    "spectral_contrast_min.3" DOUBLE PRECISION,
    "spectral_contrast_min.4" DOUBLE PRECISION,
    "spectral_contrast_min.5" DOUBLE PRECISION,
    "spectral_contrast_min.6" DOUBLE PRECISION,
    spectral_contrast_skew DOUBLE PRECISION,
    "spectral_contrast_skew.1" DOUBLE PRECISION,
    "spectral_contrast_skew.2" DOUBLE PRECISION,
    "spectral_contrast_skew.3" DOUBLE PRECISION,
    "spectral_contrast_skew.4" DOUBLE PRECISION,
    "spectral_contrast_skew.5" DOUBLE PRECISION,
    "spectral_contrast_skew.6" DOUBLE PRECISION,
    spectral_contrast_std DOUBLE PRECISION,
    "spectral_contrast_std.1" DOUBLE PRECISION,
    "spectral_contrast_std.2" DOUBLE PRECISION,
    "spectral_contrast_std.3" DOUBLE PRECISION,
    "spectral_contrast_std.4" DOUBLE PRECISION,
    "spectral_contrast_std.5" DOUBLE PRECISION,
    "spectral_contrast_std.6" DOUBLE PRECISION,
    spectral_rolloff_kurtosis DOUBLE PRECISION,
    spectral_rolloff_max DOUBLE PRECISION,
    spectral_rolloff_mean DOUBLE PRECISION,
    spectral_rolloff_median DOUBLE PRECISION,
    spectral_rolloff_min DOUBLE PRECISION,
    spectral_rolloff_skew DOUBLE PRECISION,
    spectral_rolloff_std DOUBLE PRECISION,
    tonnetz_kurtosis DOUBLE PRECISION,
    "tonnetz_kurtosis.1" DOUBLE PRECISION,
    "tonnetz_kurtosis.2" DOUBLE PRECISION,
    "tonnetz_kurtosis.3" DOUBLE PRECISION,
    "tonnetz_kurtosis.4" DOUBLE PRECISION,
    "tonnetz_kurtosis.5" DOUBLE PRECISION,
    tonnetz_max DOUBLE PRECISION,
    "tonnetz_max.1" DOUBLE PRECISION,
    "tonnetz_max.2" DOUBLE PRECISION,
    "tonnetz_max.3" DOUBLE PRECISION,
    "tonnetz_max.4" DOUBLE PRECISION,
    "tonnetz_max.5" DOUBLE PRECISION,
    tonnetz_mean DOUBLE PRECISION,
    "tonnetz_mean.1" DOUBLE PRECISION,
    "tonnetz_mean.2" DOUBLE PRECISION,
    "tonnetz_mean.3" DOUBLE PRECISION,
    "tonnetz_mean.4" DOUBLE PRECISION,
    "tonnetz_mean.5" DOUBLE PRECISION,
    tonnetz_median DOUBLE PRECISION,
    "tonnetz_median.1" DOUBLE PRECISION,
    "tonnetz_median.2" DOUBLE PRECISION,
    "tonnetz_median.3" DOUBLE PRECISION,
    "tonnetz_median.4" DOUBLE PRECISION,
    "tonnetz_median.5" DOUBLE PRECISION,
    tonnetz_min DOUBLE PRECISION,
    "tonnetz_min.1" DOUBLE PRECISION,
    "tonnetz_min.2" DOUBLE PRECISION,
    "tonnetz_min.3" DOUBLE PRECISION,
    "tonnetz_min.4" DOUBLE PRECISION,
    "tonnetz_min.5" DOUBLE PRECISION,
    tonnetz_skew DOUBLE PRECISION,
    "tonnetz_skew.1" DOUBLE PRECISION,
    "tonnetz_skew.2" DOUBLE PRECISION,
    "tonnetz_skew.3" DOUBLE PRECISION,
    "tonnetz_skew.4" DOUBLE PRECISION,
    "tonnetz_skew.5" DOUBLE PRECISION,
    tonnetz_std DOUBLE PRECISION,
    "tonnetz_std.1" DOUBLE PRECISION,
    "tonnetz_std.2" DOUBLE PRECISION,
    "tonnetz_std.3" DOUBLE PRECISION,
    "tonnetz_std.4" DOUBLE PRECISION,
    "tonnetz_std.5" DOUBLE PRECISION,
    zcr_kurtosis DOUBLE PRECISION,
    zcr_max DOUBLE PRECISION,
    zcr_mean DOUBLE PRECISION,
    zcr_median DOUBLE PRECISION,
    zcr_min DOUBLE PRECISION,
    zcr_skew DOUBLE PRECISION,
    zcr_std DOUBLE PRECISION
);

\copy stg_features FROM 'T1_analyse_de_donnees/cleaned_data/clean_features.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');

INSERT INTO temporal_feature (
    track_id,
    chroma_cens_kurtosis,
    chroma_cens_kurtosis1,
    chroma_cens_kurtosis2,
    chroma_cens_kurtosis3,
    chroma_cens_kurtosis4,
    chroma_cens_kurtosis5,
    chroma_cens_kurtosis6,
    chroma_cens_kurtosis7,
    chroma_cens_kurtosis8,
    chroma_cens_kurtosis9,
    chroma_cens_kurtosis10,
    chroma_cens_kurtosis11,
    chroma_cens_max,
    chroma_cens_max1,
    chroma_cens_max2,
    chroma_cens_max3,
    chroma_cens_max4,
    chroma_cens_max5,
    chroma_cens_max6,
    chroma_cens_max7,
    chroma_cens_max8,
    chroma_cens_max9,
    chroma_cens_max10,
    chroma_cens_max11,
    chroma_cens_mean,
    chroma_cens_mean1,
    chroma_cens_mean2,
    chroma_cens_mean3,
    chroma_cens_mean4,
    chroma_cens_mean5,
    chroma_cens_mean6,
    chroma_cens_mean7,
    chroma_cens_mean8,
    chroma_cens_mean9,
    chroma_cens_mean10,
    chroma_cens_mean11,
    chroma_cens_median,
    chroma_cens_median1,
    chroma_cens_median2,
    chroma_cens_median3,
    chroma_cens_median4,
    chroma_cens_median5,
    chroma_cens_median6,
    chroma_cens_median7,
    chroma_cens_median8,
    chroma_cens_median9,
    chroma_cens_median10,
    chroma_cens_median11,
    chroma_cens_min,
    chroma_cens_min1,
    chroma_cens_min2,
    chroma_cens_min3,
    chroma_cens_min4,
    chroma_cens_min5,
    chroma_cens_min6,
    chroma_cens_min7,
    chroma_cens_min8,
    chroma_cens_min9,
    chroma_cens_min10,
    chroma_cens_min11,
    chroma_cens_skew,
    chroma_cens_skew1,
    chroma_cens_skew2,
    chroma_cens_skew3,
    chroma_cens_skew4,
    chroma_cens_skew5,
    chroma_cens_skew6,
    chroma_cens_skew7,
    chroma_cens_skew8,
    chroma_cens_skew9,
    chroma_cens_skew10,
    chroma_cens_skew11,
    chroma_cens_std,
    chroma_cens_std1,
    chroma_cens_std2,
    chroma_cens_std3,
    chroma_cens_std4,
    chroma_cens_std5,
    chroma_cens_std6,
    chroma_cens_std7,
    chroma_cens_std8,
    chroma_cens_std9,
    chroma_cens_std10,
    chroma_cens_std11,
    chroma_cqt_kurtosis,
    chroma_cqt_kurtosis1,
    chroma_cqt_kurtosis2,
    chroma_cqt_kurtosis3,
    chroma_cqt_kurtosis4,
    chroma_cqt_kurtosis5,
    chroma_cqt_kurtosis6,
    chroma_cqt_kurtosis7,
    chroma_cqt_kurtosis8,
    chroma_cqt_kurtosis9,
    chroma_cqt_kurtosis10,
    chroma_cqt_kurtosis11,
    chroma_cqt_max,
    chroma_cqt_max1,
    chroma_cqt_max2,
    chroma_cqt_max3,
    chroma_cqt_max4,
    chroma_cqt_max5,
    chroma_cqt_max6,
    chroma_cqt_max7,
    chroma_cqt_max8,
    chroma_cqt_max9,
    chroma_cqt_max10,
    chroma_cqt_max11,
    chroma_cqt_mean,
    chroma_cqt_mean1,
    chroma_cqt_mean2,
    chroma_cqt_mean3,
    chroma_cqt_mean4,
    chroma_cqt_mean5,
    chroma_cqt_mean6,
    chroma_cqt_mean7,
    chroma_cqt_mean8,
    chroma_cqt_mean9,
    chroma_cqt_mean10,
    chroma_cqt_mean11,
    chroma_cqt_median,
    chroma_cqt_median1,
    chroma_cqt_median2,
    chroma_cqt_median3,
    chroma_cqt_median4,
    chroma_cqt_median5,
    chroma_cqt_median6,
    chroma_cqt_median7,
    chroma_cqt_median8,
    chroma_cqt_median9,
    chroma_cqt_median10,
    chroma_cqt_median11,
    chroma_cqt_min,
    chroma_cqt_min1,
    chroma_cqt_min2,
    chroma_cqt_min3,
    chroma_cqt_min4,
    chroma_cqt_min5,
    chroma_cqt_min6,
    chroma_cqt_min7,
    chroma_cqt_min8,
    chroma_cqt_min9,
    chroma_cqt_min10,
    chroma_cqt_min11,
    chroma_cqt_skew,
    chroma_cqt_skew1,
    chroma_cqt_skew2,
    chroma_cqt_skew3,
    chroma_cqt_skew4,
    chroma_cqt_skew5,
    chroma_cqt_skew6,
    chroma_cqt_skew7,
    chroma_cqt_skew8,
    chroma_cqt_skew9,
    chroma_cqt_skew10,
    chroma_cqt_skew11,
    chroma_cqt_std,
    chroma_cqt_std1,
    chroma_cqt_std2,
    chroma_cqt_std3,
    chroma_cqt_std4,
    chroma_cqt_std5,
    chroma_cqt_std6,
    chroma_cqt_std7,
    chroma_cqt_std8,
    chroma_cqt_std9,
    chroma_cqt_std10,
    chroma_cqt_std11,
    chroma_stft_kurtosis,
    chroma_stft_kurtosis1,
    chroma_stft_kurtosis2,
    chroma_stft_kurtosis3,
    chroma_stft_kurtosis4,
    chroma_stft_kurtosis5,
    chroma_stft_kurtosis6,
    chroma_stft_kurtosis7,
    chroma_stft_kurtosis8,
    chroma_stft_kurtosis9,
    chroma_stft_kurtosis10,
    chroma_stft_kurtosis11,
    chroma_stft_max,
    chroma_stft_max1,
    chroma_stft_max2,
    chroma_stft_max3,
    chroma_stft_max4,
    chroma_stft_max5,
    chroma_stft_max6,
    chroma_stft_max7,
    chroma_stft_max8,
    chroma_stft_max9,
    chroma_stft_max10,
    chroma_stft_max11,
    chroma_stft_mean,
    chroma_stft_mean1,
    chroma_stft_mean2,
    chroma_stft_mean3,
    chroma_stft_mean4,
    chroma_stft_mean5,
    chroma_stft_mean6,
    chroma_stft_mean7,
    chroma_stft_mean8,
    chroma_stft_mean9,
    chroma_stft_mean10,
    chroma_stft_mean11,
    chroma_stft_median,
    chroma_stft_median1,
    chroma_stft_median2,
    chroma_stft_median3,
    chroma_stft_median4,
    chroma_stft_median5,
    chroma_stft_median6,
    chroma_stft_median7,
    chroma_stft_median8,
    chroma_stft_median9,
    chroma_stft_median10,
    chroma_stft_median11,
    chroma_stft_min,
    chroma_stft_min1,
    chroma_stft_min2,
    chroma_stft_min3,
    chroma_stft_min4,
    chroma_stft_min5,
    chroma_stft_min6,
    chroma_stft_min7,
    chroma_stft_min8,
    chroma_stft_min9,
    chroma_stft_min10,
    chroma_stft_min11,
    chroma_stft_skew,
    chroma_stft_skew1,
    chroma_stft_skew2,
    chroma_stft_skew3,
    chroma_stft_skew4,
    chroma_stft_skew5,
    chroma_stft_skew6,
    chroma_stft_skew7,
    chroma_stft_skew8,
    chroma_stft_skew9,
    chroma_stft_skew10,
    chroma_stft_skew11,
    chroma_stft_std,
    chroma_stft_std1,
    chroma_stft_std2,
    chroma_stft_std3,
    chroma_stft_std4,
    chroma_stft_std5,
    chroma_stft_std6,
    chroma_stft_std7,
    chroma_stft_std8,
    chroma_stft_std9,
    chroma_stft_std10,
    chroma_stft_std11,
    mfcc_kurtosis,
    mfcc_kurtosis1,
    mfcc_kurtosis2,
    mfcc_kurtosis3,
    mfcc_kurtosis4,
    mfcc_kurtosis5,
    mfcc_kurtosis6,
    mfcc_kurtosis7,
    mfcc_kurtosis8,
    mfcc_kurtosis9,
    mfcc_kurtosis10,
    mfcc_kurtosis11,
    mfcc_kurtosis12,
    mfcc_kurtosis13,
    mfcc_kurtosis14,
    mfcc_kurtosis15,
    mfcc_kurtosis16,
    mfcc_kurtosis17,
    mfcc_kurtosis18,
    mfcc_kurtosis19,
    mfcc_max,
    mfcc_max1,
    mfcc_max2,
    mfcc_max3,
    mfcc_max4,
    mfcc_max5,
    mfcc_max6,
    mfcc_max7,
    mfcc_max8,
    mfcc_max9,
    mfcc_max10,
    mfcc_max11,
    mfcc_max12,
    mfcc_max13,
    mfcc_max14,
    mfcc_max15,
    mfcc_max16,
    mfcc_max17,
    mfcc_max18,
    mfcc_max19,
    mfcc_mean,
    mfcc_mean1,
    mfcc_mean2,
    mfcc_mean3,
    mfcc_mean4,
    mfcc_mean5,
    mfcc_mean6,
    mfcc_mean7,
    mfcc_mean8,
    mfcc_mean9,
    mfcc_mean10,
    mfcc_mean11,
    mfcc_mean12,
    mfcc_mean13,
    mfcc_mean14,
    mfcc_mean15,
    mfcc_mean16,
    mfcc_mean17,
    mfcc_mean18,
    mfcc_mean19,
    mfcc_median,
    mfcc_median1,
    mfcc_median2,
    mfcc_median3,
    mfcc_median4,
    mfcc_median5,
    mfcc_median6,
    mfcc_median7,
    mfcc_median8,
    mfcc_median9,
    mfcc_median10,
    mfcc_median11,
    mfcc_median12,
    mfcc_median13,
    mfcc_median14,
    mfcc_median15,
    mfcc_median16,
    mfcc_median17,
    mfcc_median18,
    mfcc_median19,
    mfcc_min,
    mfcc_min1,
    mfcc_min2,
    mfcc_min3,
    mfcc_min4,
    mfcc_min5,
    mfcc_min6,
    mfcc_min7,
    mfcc_min8,
    mfcc_min9,
    mfcc_min10,
    mfcc_min11,
    mfcc_min12,
    mfcc_min13,
    mfcc_min14,
    mfcc_min15,
    mfcc_min16,
    mfcc_min17,
    mfcc_min18,
    mfcc_min19,
    mfcc_skew,
    mfcc_skew1,
    mfcc_skew2,
    mfcc_skew3,
    mfcc_skew4,
    mfcc_skew5,
    mfcc_skew6,
    mfcc_skew7,
    mfcc_skew8,
    mfcc_skew9,
    mfcc_skew10,
    mfcc_skew11,
    mfcc_skew12,
    mfcc_skew13,
    mfcc_skew14,
    mfcc_skew15,
    mfcc_skew16,
    mfcc_skew17,
    mfcc_skew18,
    mfcc_skew19,
    mfcc_std,
    mfcc_std1,
    mfcc_std2,
    mfcc_std3,
    mfcc_std4,
    mfcc_std5,
    mfcc_std6,
    mfcc_std7,
    mfcc_std8,
    mfcc_std9,
    mfcc_std10,
    mfcc_std11,
    mfcc_std12,
    mfcc_std13,
    mfcc_std14,
    mfcc_std15,
    mfcc_std16,
    mfcc_std17,
    mfcc_std18,
    mfcc_std19,
    rmse_kurtosis,
    rmse_max,
    rmse_mean,
    rmse_median,
    rmse_min,
    rmse_skew,
    rmse_std,
    spectral_bandwidth_kurtosis,
    spectral_bandwidth_max,
    spectral_bandwidth_mean,
    spectral_bandwidth_median,
    spectral_bandwidth_min,
    spectral_bandwidth_skew,
    spectral_bandwidth_std,
    spectral_centroid_kurtosis,
    spectral_centroid_max,
    spectral_centroid_mean,
    spectral_centroid_median,
    spectral_centroid_min,
    spectral_centroid_skew,
    spectral_centroid_std,
    spectral_contrast_kurtosis,
    spectral_contrast_kurtosis1,
    spectral_contrast_kurtosis2,
    spectral_contrast_kurtosis3,
    spectral_contrast_kurtosis4,
    spectral_contrast_kurtosis5,
    spectral_contrast_kurtosis6,
    spectral_contrast_max,
    spectral_contrast_max1,
    spectral_contrast_max2,
    spectral_contrast_max3,
    spectral_contrast_max4,
    spectral_contrast_max5,
    spectral_contrast_max6,
    spectral_contrast_mean,
    spectral_contrast_mean1,
    spectral_contrast_mean2,
    spectral_contrast_mean3,
    spectral_contrast_mean4,
    spectral_contrast_mean5,
    spectral_contrast_mean6,
    spectral_contrast_median,
    spectral_contrast_median1,
    spectral_contrast_median2,
    spectral_contrast_median3,
    spectral_contrast_median4,
    spectral_contrast_median5,
    spectral_contrast_median6,
    spectral_contrast_min,
    spectral_contrast_min1,
    spectral_contrast_min2,
    spectral_contrast_min3,
    spectral_contrast_min4,
    spectral_contrast_min5,
    spectral_contrast_min6,
    spectral_contrast_skew,
    spectral_contrast_skew1,
    spectral_contrast_skew2,
    spectral_contrast_skew3,
    spectral_contrast_skew4,
    spectral_contrast_skew5,
    spectral_contrast_skew6,
    spectral_contrast_std,
    spectral_contrast_std1,
    spectral_contrast_std2,
    spectral_contrast_std3,
    spectral_contrast_std4,
    spectral_contrast_std5,
    spectral_contrast_std6,
    spectral_rolloff_kurtosis,
    spectral_rolloff_max,
    spectral_rolloff_mean,
    spectral_rolloff_median,
    spectral_rolloff_min,
    spectral_rolloff_skew,
    spectral_rolloff_std,
    tonnetz_kurtosis,
    tonnetz_kurtosis1,
    tonnetz_kurtosis2,
    tonnetz_kurtosis3,
    tonnetz_kurtosis4,
    tonnetz_kurtosis5,
    tonnetz_max,
    tonnetz_max1,
    tonnetz_max2,
    tonnetz_max3,
    tonnetz_max4,
    tonnetz_max5,
    tonnetz_mean,
    tonnetz_mean1,
    tonnetz_mean2,
    tonnetz_mean3,
    tonnetz_mean4,
    tonnetz_mean5,
    tonnetz_median,
    tonnetz_median1,
    tonnetz_median2,
    tonnetz_median3,
    tonnetz_median4,
    tonnetz_median5,
    tonnetz_min,
    tonnetz_min1,
    tonnetz_min2,
    tonnetz_min3,
    tonnetz_min4,
    tonnetz_min5,
    tonnetz_skew,
    tonnetz_skew1,
    tonnetz_skew2,
    tonnetz_skew3,
    tonnetz_skew4,
    tonnetz_skew5,
    tonnetz_std,
    tonnetz_std1,
    tonnetz_std2,
    tonnetz_std3,
    tonnetz_std4,
    tonnetz_std5,
    zcr_kurtosis,
    zcr_max,
    zcr_mean,
    zcr_median,
    zcr_min,
    zcr_skew,
    zcr_std
)
SELECT
    m.new_uuid,
    s.chroma_cens_kurtosis,
    s."chroma_cens_kurtosis.1",
    s."chroma_cens_kurtosis.2",
    s."chroma_cens_kurtosis.3",
    s."chroma_cens_kurtosis.4",
    s."chroma_cens_kurtosis.5",
    s."chroma_cens_kurtosis.6",
    s."chroma_cens_kurtosis.7",
    s."chroma_cens_kurtosis.8",
    s."chroma_cens_kurtosis.9",
    s."chroma_cens_kurtosis.10",
    s."chroma_cens_kurtosis.11",
    s.chroma_cens_max,
    s."chroma_cens_max.1",
    s."chroma_cens_max.2",
    s."chroma_cens_max.3",
    s."chroma_cens_max.4",
    s."chroma_cens_max.5",
    s."chroma_cens_max.6",
    s."chroma_cens_max.7",
    s."chroma_cens_max.8",
    s."chroma_cens_max.9",
    s."chroma_cens_max.10",
    s."chroma_cens_max.11",
    s.chroma_cens_mean,
    s."chroma_cens_mean.1",
    s."chroma_cens_mean.2",
    s."chroma_cens_mean.3",
    s."chroma_cens_mean.4",
    s."chroma_cens_mean.5",
    s."chroma_cens_mean.6",
    s."chroma_cens_mean.7",
    s."chroma_cens_mean.8",
    s."chroma_cens_mean.9",
    s."chroma_cens_mean.10",
    s."chroma_cens_mean.11",
    s.chroma_cens_median,
    s."chroma_cens_median.1",
    s."chroma_cens_median.2",
    s."chroma_cens_median.3",
    s."chroma_cens_median.4",
    s."chroma_cens_median.5",
    s."chroma_cens_median.6",
    s."chroma_cens_median.7",
    s."chroma_cens_median.8",
    s."chroma_cens_median.9",
    s."chroma_cens_median.10",
    s."chroma_cens_median.11",
    s.chroma_cens_min,
    s."chroma_cens_min.1",
    s."chroma_cens_min.2",
    s."chroma_cens_min.3",
    s."chroma_cens_min.4",
    s."chroma_cens_min.5",
    s."chroma_cens_min.6",
    s."chroma_cens_min.7",
    s."chroma_cens_min.8",
    s."chroma_cens_min.9",
    s."chroma_cens_min.10",
    s."chroma_cens_min.11",
    s.chroma_cens_skew,
    s."chroma_cens_skew.1",
    s."chroma_cens_skew.2",
    s."chroma_cens_skew.3",
    s."chroma_cens_skew.4",
    s."chroma_cens_skew.5",
    s."chroma_cens_skew.6",
    s."chroma_cens_skew.7",
    s."chroma_cens_skew.8",
    s."chroma_cens_skew.9",
    s."chroma_cens_skew.10",
    s."chroma_cens_skew.11",
    s.chroma_cens_std,
    s."chroma_cens_std.1",
    s."chroma_cens_std.2",
    s."chroma_cens_std.3",
    s."chroma_cens_std.4",
    s."chroma_cens_std.5",
    s."chroma_cens_std.6",
    s."chroma_cens_std.7",
    s."chroma_cens_std.8",
    s."chroma_cens_std.9",
    s."chroma_cens_std.10",
    s."chroma_cens_std.11",
    s.chroma_cqt_kurtosis,
    s."chroma_cqt_kurtosis.1",
    s."chroma_cqt_kurtosis.2",
    s."chroma_cqt_kurtosis.3",
    s."chroma_cqt_kurtosis.4",
    s."chroma_cqt_kurtosis.5",
    s."chroma_cqt_kurtosis.6",
    s."chroma_cqt_kurtosis.7",
    s."chroma_cqt_kurtosis.8",
    s."chroma_cqt_kurtosis.9",
    s."chroma_cqt_kurtosis.10",
    s."chroma_cqt_kurtosis.11",
    s.chroma_cqt_max,
    s."chroma_cqt_max.1",
    s."chroma_cqt_max.2",
    s."chroma_cqt_max.3",
    s."chroma_cqt_max.4",
    s."chroma_cqt_max.5",
    s."chroma_cqt_max.6",
    s."chroma_cqt_max.7",
    s."chroma_cqt_max.8",
    s."chroma_cqt_max.9",
    s."chroma_cqt_max.10",
    s."chroma_cqt_max.11",
    s.chroma_cqt_mean,
    s."chroma_cqt_mean.1",
    s."chroma_cqt_mean.2",
    s."chroma_cqt_mean.3",
    s."chroma_cqt_mean.4",
    s."chroma_cqt_mean.5",
    s."chroma_cqt_mean.6",
    s."chroma_cqt_mean.7",
    s."chroma_cqt_mean.8",
    s."chroma_cqt_mean.9",
    s."chroma_cqt_mean.10",
    s."chroma_cqt_mean.11",
    s.chroma_cqt_median,
    s."chroma_cqt_median.1",
    s."chroma_cqt_median.2",
    s."chroma_cqt_median.3",
    s."chroma_cqt_median.4",
    s."chroma_cqt_median.5",
    s."chroma_cqt_median.6",
    s."chroma_cqt_median.7",
    s."chroma_cqt_median.8",
    s."chroma_cqt_median.9",
    s."chroma_cqt_median.10",
    s."chroma_cqt_median.11",
    s.chroma_cqt_min,
    s."chroma_cqt_min.1",
    s."chroma_cqt_min.2",
    s."chroma_cqt_min.3",
    s."chroma_cqt_min.4",
    s."chroma_cqt_min.5",
    s."chroma_cqt_min.6",
    s."chroma_cqt_min.7",
    s."chroma_cqt_min.8",
    s."chroma_cqt_min.9",
    s."chroma_cqt_min.10",
    s."chroma_cqt_min.11",
    s.chroma_cqt_skew,
    s."chroma_cqt_skew.1",
    s."chroma_cqt_skew.2",
    s."chroma_cqt_skew.3",
    s."chroma_cqt_skew.4",
    s."chroma_cqt_skew.5",
    s."chroma_cqt_skew.6",
    s."chroma_cqt_skew.7",
    s."chroma_cqt_skew.8",
    s."chroma_cqt_skew.9",
    s."chroma_cqt_skew.10",
    s."chroma_cqt_skew.11",
    s.chroma_cqt_std,
    s."chroma_cqt_std.1",
    s."chroma_cqt_std.2",
    s."chroma_cqt_std.3",
    s."chroma_cqt_std.4",
    s."chroma_cqt_std.5",
    s."chroma_cqt_std.6",
    s."chroma_cqt_std.7",
    s."chroma_cqt_std.8",
    s."chroma_cqt_std.9",
    s."chroma_cqt_std.10",
    s."chroma_cqt_std.11",
    s.chroma_stft_kurtosis,
    s."chroma_stft_kurtosis.1",
    s."chroma_stft_kurtosis.2",
    s."chroma_stft_kurtosis.3",
    s."chroma_stft_kurtosis.4",
    s."chroma_stft_kurtosis.5",
    s."chroma_stft_kurtosis.6",
    s."chroma_stft_kurtosis.7",
    s."chroma_stft_kurtosis.8",
    s."chroma_stft_kurtosis.9",
    s."chroma_stft_kurtosis.10",
    s."chroma_stft_kurtosis.11",
    s.chroma_stft_max,
    s."chroma_stft_max.1",
    s."chroma_stft_max.2",
    s."chroma_stft_max.3",
    s."chroma_stft_max.4",
    s."chroma_stft_max.5",
    s."chroma_stft_max.6",
    s."chroma_stft_max.7",
    s."chroma_stft_max.8",
    s."chroma_stft_max.9",
    s."chroma_stft_max.10",
    s."chroma_stft_max.11",
    s.chroma_stft_mean,
    s."chroma_stft_mean.1",
    s."chroma_stft_mean.2",
    s."chroma_stft_mean.3",
    s."chroma_stft_mean.4",
    s."chroma_stft_mean.5",
    s."chroma_stft_mean.6",
    s."chroma_stft_mean.7",
    s."chroma_stft_mean.8",
    s."chroma_stft_mean.9",
    s."chroma_stft_mean.10",
    s."chroma_stft_mean.11",
    s.chroma_stft_median,
    s."chroma_stft_median.1",
    s."chroma_stft_median.2",
    s."chroma_stft_median.3",
    s."chroma_stft_median.4",
    s."chroma_stft_median.5",
    s."chroma_stft_median.6",
    s."chroma_stft_median.7",
    s."chroma_stft_median.8",
    s."chroma_stft_median.9",
    s."chroma_stft_median.10",
    s."chroma_stft_median.11",
    s.chroma_stft_min,
    s."chroma_stft_min.1",
    s."chroma_stft_min.2",
    s."chroma_stft_min.3",
    s."chroma_stft_min.4",
    s."chroma_stft_min.5",
    s."chroma_stft_min.6",
    s."chroma_stft_min.7",
    s."chroma_stft_min.8",
    s."chroma_stft_min.9",
    s."chroma_stft_min.10",
    s."chroma_stft_min.11",
    s.chroma_stft_skew,
    s."chroma_stft_skew.1",
    s."chroma_stft_skew.2",
    s."chroma_stft_skew.3",
    s."chroma_stft_skew.4",
    s."chroma_stft_skew.5",
    s."chroma_stft_skew.6",
    s."chroma_stft_skew.7",
    s."chroma_stft_skew.8",
    s."chroma_stft_skew.9",
    s."chroma_stft_skew.10",
    s."chroma_stft_skew.11",
    s.chroma_stft_std,
    s."chroma_stft_std.1",
    s."chroma_stft_std.2",
    s."chroma_stft_std.3",
    s."chroma_stft_std.4",
    s."chroma_stft_std.5",
    s."chroma_stft_std.6",
    s."chroma_stft_std.7",
    s."chroma_stft_std.8",
    s."chroma_stft_std.9",
    s."chroma_stft_std.10",
    s."chroma_stft_std.11",
    s.mfcc_kurtosis,
    s."mfcc_kurtosis.1",
    s."mfcc_kurtosis.2",
    s."mfcc_kurtosis.3",
    s."mfcc_kurtosis.4",
    s."mfcc_kurtosis.5",
    s."mfcc_kurtosis.6",
    s."mfcc_kurtosis.7",
    s."mfcc_kurtosis.8",
    s."mfcc_kurtosis.9",
    s."mfcc_kurtosis.10",
    s."mfcc_kurtosis.11",
    s."mfcc_kurtosis.12",
    s."mfcc_kurtosis.13",
    s."mfcc_kurtosis.14",
    s."mfcc_kurtosis.15",
    s."mfcc_kurtosis.16",
    s."mfcc_kurtosis.17",
    s."mfcc_kurtosis.18",
    s."mfcc_kurtosis.19",
    s.mfcc_max,
    s."mfcc_max.1",
    s."mfcc_max.2",
    s."mfcc_max.3",
    s."mfcc_max.4",
    s."mfcc_max.5",
    s."mfcc_max.6",
    s."mfcc_max.7",
    s."mfcc_max.8",
    s."mfcc_max.9",
    s."mfcc_max.10",
    s."mfcc_max.11",
    s."mfcc_max.12",
    s."mfcc_max.13",
    s."mfcc_max.14",
    s."mfcc_max.15",
    s."mfcc_max.16",
    s."mfcc_max.17",
    s."mfcc_max.18",
    s."mfcc_max.19",
    s.mfcc_mean,
    s."mfcc_mean.1",
    s."mfcc_mean.2",
    s."mfcc_mean.3",
    s."mfcc_mean.4",
    s."mfcc_mean.5",
    s."mfcc_mean.6",
    s."mfcc_mean.7",
    s."mfcc_mean.8",
    s."mfcc_mean.9",
    s."mfcc_mean.10",
    s."mfcc_mean.11",
    s."mfcc_mean.12",
    s."mfcc_mean.13",
    s."mfcc_mean.14",
    s."mfcc_mean.15",
    s."mfcc_mean.16",
    s."mfcc_mean.17",
    s."mfcc_mean.18",
    s."mfcc_mean.19",
    s.mfcc_median,
    s."mfcc_median.1",
    s."mfcc_median.2",
    s."mfcc_median.3",
    s."mfcc_median.4",
    s."mfcc_median.5",
    s."mfcc_median.6",
    s."mfcc_median.7",
    s."mfcc_median.8",
    s."mfcc_median.9",
    s."mfcc_median.10",
    s."mfcc_median.11",
    s."mfcc_median.12",
    s."mfcc_median.13",
    s."mfcc_median.14",
    s."mfcc_median.15",
    s."mfcc_median.16",
    s."mfcc_median.17",
    s."mfcc_median.18",
    s."mfcc_median.19",
    s.mfcc_min,
    s."mfcc_min.1",
    s."mfcc_min.2",
    s."mfcc_min.3",
    s."mfcc_min.4",
    s."mfcc_min.5",
    s."mfcc_min.6",
    s."mfcc_min.7",
    s."mfcc_min.8",
    s."mfcc_min.9",
    s."mfcc_min.10",
    s."mfcc_min.11",
    s."mfcc_min.12",
    s."mfcc_min.13",
    s."mfcc_min.14",
    s."mfcc_min.15",
    s."mfcc_min.16",
    s."mfcc_min.17",
    s."mfcc_min.18",
    s."mfcc_min.19",
    s.mfcc_skew,
    s."mfcc_skew.1",
    s."mfcc_skew.2",
    s."mfcc_skew.3",
    s."mfcc_skew.4",
    s."mfcc_skew.5",
    s."mfcc_skew.6",
    s."mfcc_skew.7",
    s."mfcc_skew.8",
    s."mfcc_skew.9",
    s."mfcc_skew.10",
    s."mfcc_skew.11",
    s."mfcc_skew.12",
    s."mfcc_skew.13",
    s."mfcc_skew.14",
    s."mfcc_skew.15",
    s."mfcc_skew.16",
    s."mfcc_skew.17",
    s."mfcc_skew.18",
    s."mfcc_skew.19",
    s.mfcc_std,
    s."mfcc_std.1",
    s."mfcc_std.2",
    s."mfcc_std.3",
    s."mfcc_std.4",
    s."mfcc_std.5",
    s."mfcc_std.6",
    s."mfcc_std.7",
    s."mfcc_std.8",
    s."mfcc_std.9",
    s."mfcc_std.10",
    s."mfcc_std.11",
    s."mfcc_std.12",
    s."mfcc_std.13",
    s."mfcc_std.14",
    s."mfcc_std.15",
    s."mfcc_std.16",
    s."mfcc_std.17",
    s."mfcc_std.18",
    s."mfcc_std.19",
    s.rmse_kurtosis,
    s.rmse_max,
    s.rmse_mean,
    s.rmse_median,
    s.rmse_min,
    s.rmse_skew,
    s.rmse_std,
    s.spectral_bandwidth_kurtosis,
    s.spectral_bandwidth_max,
    s.spectral_bandwidth_mean,
    s.spectral_bandwidth_median,
    s.spectral_bandwidth_min,
    s.spectral_bandwidth_skew,
    s.spectral_bandwidth_std,
    s.spectral_centroid_kurtosis,
    s.spectral_centroid_max,
    s.spectral_centroid_mean,
    s.spectral_centroid_median,
    s.spectral_centroid_min,
    s.spectral_centroid_skew,
    s.spectral_centroid_std,
    s.spectral_contrast_kurtosis,
    s."spectral_contrast_kurtosis.1",
    s."spectral_contrast_kurtosis.2",
    s."spectral_contrast_kurtosis.3",
    s."spectral_contrast_kurtosis.4",
    s."spectral_contrast_kurtosis.5",
    s."spectral_contrast_kurtosis.6",
    s.spectral_contrast_max,
    s."spectral_contrast_max.1",
    s."spectral_contrast_max.2",
    s."spectral_contrast_max.3",
    s."spectral_contrast_max.4",
    s."spectral_contrast_max.5",
    s."spectral_contrast_max.6",
    s.spectral_contrast_mean,
    s."spectral_contrast_mean.1",
    s."spectral_contrast_mean.2",
    s."spectral_contrast_mean.3",
    s."spectral_contrast_mean.4",
    s."spectral_contrast_mean.5",
    s."spectral_contrast_mean.6",
    s.spectral_contrast_median,
    s."spectral_contrast_median.1",
    s."spectral_contrast_median.2",
    s."spectral_contrast_median.3",
    s."spectral_contrast_median.4",
    s."spectral_contrast_median.5",
    s."spectral_contrast_median.6",
    s.spectral_contrast_min,
    s."spectral_contrast_min.1",
    s."spectral_contrast_min.2",
    s."spectral_contrast_min.3",
    s."spectral_contrast_min.4",
    s."spectral_contrast_min.5",
    s."spectral_contrast_min.6",
    s.spectral_contrast_skew,
    s."spectral_contrast_skew.1",
    s."spectral_contrast_skew.2",
    s."spectral_contrast_skew.3",
    s."spectral_contrast_skew.4",
    s."spectral_contrast_skew.5",
    s."spectral_contrast_skew.6",
    s.spectral_contrast_std,
    s."spectral_contrast_std.1",
    s."spectral_contrast_std.2",
    s."spectral_contrast_std.3",
    s."spectral_contrast_std.4",
    s."spectral_contrast_std.5",
    s."spectral_contrast_std.6",
    s.spectral_rolloff_kurtosis,
    s.spectral_rolloff_max,
    s.spectral_rolloff_mean,
    s.spectral_rolloff_median,
    s.spectral_rolloff_min,
    s.spectral_rolloff_skew,
    s.spectral_rolloff_std,
    s.tonnetz_kurtosis,
    s."tonnetz_kurtosis.1",
    s."tonnetz_kurtosis.2",
    s."tonnetz_kurtosis.3",
    s."tonnetz_kurtosis.4",
    s."tonnetz_kurtosis.5",
    s.tonnetz_max,
    s."tonnetz_max.1",
    s."tonnetz_max.2",
    s."tonnetz_max.3",
    s."tonnetz_max.4",
    s."tonnetz_max.5",
    s.tonnetz_mean,
    s."tonnetz_mean.1",
    s."tonnetz_mean.2",
    s."tonnetz_mean.3",
    s."tonnetz_mean.4",
    s."tonnetz_mean.5",
    s.tonnetz_median,
    s."tonnetz_median.1",
    s."tonnetz_median.2",
    s."tonnetz_median.3",
    s."tonnetz_median.4",
    s."tonnetz_median.5",
    s.tonnetz_min,
    s."tonnetz_min.1",
    s."tonnetz_min.2",
    s."tonnetz_min.3",
    s."tonnetz_min.4",
    s."tonnetz_min.5",
    s.tonnetz_skew,
    s."tonnetz_skew.1",
    s."tonnetz_skew.2",
    s."tonnetz_skew.3",
    s."tonnetz_skew.4",
    s."tonnetz_skew.5",
    s.tonnetz_std,
    s."tonnetz_std.1",
    s."tonnetz_std.2",
    s."tonnetz_std.3",
    s."tonnetz_std.4",
    s."tonnetz_std.5",
    s.zcr_kurtosis,
    s.zcr_max,
    s.zcr_mean,
    s.zcr_median,
    s.zcr_min,
    s.zcr_skew,
    s.zcr_std
FROM stg_features s
JOIN _legacy_id_map m ON m.old_id = s.track_id AND m.table_name = 'track'
ON CONFLICT (track_id) DO UPDATE SET
    chroma_cens_kurtosis = EXCLUDED.chroma_cens_kurtosis,
    chroma_cens_kurtosis1 = EXCLUDED.chroma_cens_kurtosis1,
    chroma_cens_kurtosis2 = EXCLUDED.chroma_cens_kurtosis2,
    chroma_cens_kurtosis3 = EXCLUDED.chroma_cens_kurtosis3,
    chroma_cens_kurtosis4 = EXCLUDED.chroma_cens_kurtosis4,
    chroma_cens_kurtosis5 = EXCLUDED.chroma_cens_kurtosis5,
    chroma_cens_kurtosis6 = EXCLUDED.chroma_cens_kurtosis6,
    chroma_cens_kurtosis7 = EXCLUDED.chroma_cens_kurtosis7,
    chroma_cens_kurtosis8 = EXCLUDED.chroma_cens_kurtosis8,
    chroma_cens_kurtosis9 = EXCLUDED.chroma_cens_kurtosis9,
    chroma_cens_kurtosis10 = EXCLUDED.chroma_cens_kurtosis10,
    chroma_cens_kurtosis11 = EXCLUDED.chroma_cens_kurtosis11,
    chroma_cens_max = EXCLUDED.chroma_cens_max,
    chroma_cens_max1 = EXCLUDED.chroma_cens_max1,
    chroma_cens_max2 = EXCLUDED.chroma_cens_max2,
    chroma_cens_max3 = EXCLUDED.chroma_cens_max3,
    chroma_cens_max4 = EXCLUDED.chroma_cens_max4,
    chroma_cens_max5 = EXCLUDED.chroma_cens_max5,
    chroma_cens_max6 = EXCLUDED.chroma_cens_max6,
    chroma_cens_max7 = EXCLUDED.chroma_cens_max7,
    chroma_cens_max8 = EXCLUDED.chroma_cens_max8,
    chroma_cens_max9 = EXCLUDED.chroma_cens_max9,
    chroma_cens_max10 = EXCLUDED.chroma_cens_max10,
    chroma_cens_max11 = EXCLUDED.chroma_cens_max11,
    chroma_cens_mean = EXCLUDED.chroma_cens_mean,
    chroma_cens_mean1 = EXCLUDED.chroma_cens_mean1,
    chroma_cens_mean2 = EXCLUDED.chroma_cens_mean2,
    chroma_cens_mean3 = EXCLUDED.chroma_cens_mean3,
    chroma_cens_mean4 = EXCLUDED.chroma_cens_mean4,
    chroma_cens_mean5 = EXCLUDED.chroma_cens_mean5,
    chroma_cens_mean6 = EXCLUDED.chroma_cens_mean6,
    chroma_cens_mean7 = EXCLUDED.chroma_cens_mean7,
    chroma_cens_mean8 = EXCLUDED.chroma_cens_mean8,
    chroma_cens_mean9 = EXCLUDED.chroma_cens_mean9,
    chroma_cens_mean10 = EXCLUDED.chroma_cens_mean10,
    chroma_cens_mean11 = EXCLUDED.chroma_cens_mean11,
    chroma_cens_median = EXCLUDED.chroma_cens_median,
    chroma_cens_median1 = EXCLUDED.chroma_cens_median1,
    chroma_cens_median2 = EXCLUDED.chroma_cens_median2,
    chroma_cens_median3 = EXCLUDED.chroma_cens_median3,
    chroma_cens_median4 = EXCLUDED.chroma_cens_median4,
    chroma_cens_median5 = EXCLUDED.chroma_cens_median5,
    chroma_cens_median6 = EXCLUDED.chroma_cens_median6,
    chroma_cens_median7 = EXCLUDED.chroma_cens_median7,
    chroma_cens_median8 = EXCLUDED.chroma_cens_median8,
    chroma_cens_median9 = EXCLUDED.chroma_cens_median9,
    chroma_cens_median10 = EXCLUDED.chroma_cens_median10,
    chroma_cens_median11 = EXCLUDED.chroma_cens_median11,
    chroma_cens_min = EXCLUDED.chroma_cens_min,
    chroma_cens_min1 = EXCLUDED.chroma_cens_min1,
    chroma_cens_min2 = EXCLUDED.chroma_cens_min2,
    chroma_cens_min3 = EXCLUDED.chroma_cens_min3,
    chroma_cens_min4 = EXCLUDED.chroma_cens_min4,
    chroma_cens_min5 = EXCLUDED.chroma_cens_min5,
    chroma_cens_min6 = EXCLUDED.chroma_cens_min6,
    chroma_cens_min7 = EXCLUDED.chroma_cens_min7,
    chroma_cens_min8 = EXCLUDED.chroma_cens_min8,
    chroma_cens_min9 = EXCLUDED.chroma_cens_min9,
    chroma_cens_min10 = EXCLUDED.chroma_cens_min10,
    chroma_cens_min11 = EXCLUDED.chroma_cens_min11,
    chroma_cens_skew = EXCLUDED.chroma_cens_skew,
    chroma_cens_skew1 = EXCLUDED.chroma_cens_skew1,
    chroma_cens_skew2 = EXCLUDED.chroma_cens_skew2,
    chroma_cens_skew3 = EXCLUDED.chroma_cens_skew3,
    chroma_cens_skew4 = EXCLUDED.chroma_cens_skew4,
    chroma_cens_skew5 = EXCLUDED.chroma_cens_skew5,
    chroma_cens_skew6 = EXCLUDED.chroma_cens_skew6,
    chroma_cens_skew7 = EXCLUDED.chroma_cens_skew7,
    chroma_cens_skew8 = EXCLUDED.chroma_cens_skew8,
    chroma_cens_skew9 = EXCLUDED.chroma_cens_skew9,
    chroma_cens_skew10 = EXCLUDED.chroma_cens_skew10,
    chroma_cens_skew11 = EXCLUDED.chroma_cens_skew11,
    chroma_cens_std = EXCLUDED.chroma_cens_std,
    chroma_cens_std1 = EXCLUDED.chroma_cens_std1,
    chroma_cens_std2 = EXCLUDED.chroma_cens_std2,
    chroma_cens_std3 = EXCLUDED.chroma_cens_std3,
    chroma_cens_std4 = EXCLUDED.chroma_cens_std4,
    chroma_cens_std5 = EXCLUDED.chroma_cens_std5,
    chroma_cens_std6 = EXCLUDED.chroma_cens_std6,
    chroma_cens_std7 = EXCLUDED.chroma_cens_std7,
    chroma_cens_std8 = EXCLUDED.chroma_cens_std8,
    chroma_cens_std9 = EXCLUDED.chroma_cens_std9,
    chroma_cens_std10 = EXCLUDED.chroma_cens_std10,
    chroma_cens_std11 = EXCLUDED.chroma_cens_std11,
    chroma_cqt_kurtosis = EXCLUDED.chroma_cqt_kurtosis,
    chroma_cqt_kurtosis1 = EXCLUDED.chroma_cqt_kurtosis1,
    chroma_cqt_kurtosis2 = EXCLUDED.chroma_cqt_kurtosis2,
    chroma_cqt_kurtosis3 = EXCLUDED.chroma_cqt_kurtosis3,
    chroma_cqt_kurtosis4 = EXCLUDED.chroma_cqt_kurtosis4,
    chroma_cqt_kurtosis5 = EXCLUDED.chroma_cqt_kurtosis5,
    chroma_cqt_kurtosis6 = EXCLUDED.chroma_cqt_kurtosis6,
    chroma_cqt_kurtosis7 = EXCLUDED.chroma_cqt_kurtosis7,
    chroma_cqt_kurtosis8 = EXCLUDED.chroma_cqt_kurtosis8,
    chroma_cqt_kurtosis9 = EXCLUDED.chroma_cqt_kurtosis9,
    chroma_cqt_kurtosis10 = EXCLUDED.chroma_cqt_kurtosis10,
    chroma_cqt_kurtosis11 = EXCLUDED.chroma_cqt_kurtosis11,
    chroma_cqt_max = EXCLUDED.chroma_cqt_max,
    chroma_cqt_max1 = EXCLUDED.chroma_cqt_max1,
    chroma_cqt_max2 = EXCLUDED.chroma_cqt_max2,
    chroma_cqt_max3 = EXCLUDED.chroma_cqt_max3,
    chroma_cqt_max4 = EXCLUDED.chroma_cqt_max4,
    chroma_cqt_max5 = EXCLUDED.chroma_cqt_max5,
    chroma_cqt_max6 = EXCLUDED.chroma_cqt_max6,
    chroma_cqt_max7 = EXCLUDED.chroma_cqt_max7,
    chroma_cqt_max8 = EXCLUDED.chroma_cqt_max8,
    chroma_cqt_max9 = EXCLUDED.chroma_cqt_max9,
    chroma_cqt_max10 = EXCLUDED.chroma_cqt_max10,
    chroma_cqt_max11 = EXCLUDED.chroma_cqt_max11,
    chroma_cqt_mean = EXCLUDED.chroma_cqt_mean,
    chroma_cqt_mean1 = EXCLUDED.chroma_cqt_mean1,
    chroma_cqt_mean2 = EXCLUDED.chroma_cqt_mean2,
    chroma_cqt_mean3 = EXCLUDED.chroma_cqt_mean3,
    chroma_cqt_mean4 = EXCLUDED.chroma_cqt_mean4,
    chroma_cqt_mean5 = EXCLUDED.chroma_cqt_mean5,
    chroma_cqt_mean6 = EXCLUDED.chroma_cqt_mean6,
    chroma_cqt_mean7 = EXCLUDED.chroma_cqt_mean7,
    chroma_cqt_mean8 = EXCLUDED.chroma_cqt_mean8,
    chroma_cqt_mean9 = EXCLUDED.chroma_cqt_mean9,
    chroma_cqt_mean10 = EXCLUDED.chroma_cqt_mean10,
    chroma_cqt_mean11 = EXCLUDED.chroma_cqt_mean11,
    chroma_cqt_median = EXCLUDED.chroma_cqt_median,
    chroma_cqt_median1 = EXCLUDED.chroma_cqt_median1,
    chroma_cqt_median2 = EXCLUDED.chroma_cqt_median2,
    chroma_cqt_median3 = EXCLUDED.chroma_cqt_median3,
    chroma_cqt_median4 = EXCLUDED.chroma_cqt_median4,
    chroma_cqt_median5 = EXCLUDED.chroma_cqt_median5,
    chroma_cqt_median6 = EXCLUDED.chroma_cqt_median6,
    chroma_cqt_median7 = EXCLUDED.chroma_cqt_median7,
    chroma_cqt_median8 = EXCLUDED.chroma_cqt_median8,
    chroma_cqt_median9 = EXCLUDED.chroma_cqt_median9,
    chroma_cqt_median10 = EXCLUDED.chroma_cqt_median10,
    chroma_cqt_median11 = EXCLUDED.chroma_cqt_median11,
    chroma_cqt_min = EXCLUDED.chroma_cqt_min,
    chroma_cqt_min1 = EXCLUDED.chroma_cqt_min1,
    chroma_cqt_min2 = EXCLUDED.chroma_cqt_min2,
    chroma_cqt_min3 = EXCLUDED.chroma_cqt_min3,
    chroma_cqt_min4 = EXCLUDED.chroma_cqt_min4,
    chroma_cqt_min5 = EXCLUDED.chroma_cqt_min5,
    chroma_cqt_min6 = EXCLUDED.chroma_cqt_min6,
    chroma_cqt_min7 = EXCLUDED.chroma_cqt_min7,
    chroma_cqt_min8 = EXCLUDED.chroma_cqt_min8,
    chroma_cqt_min9 = EXCLUDED.chroma_cqt_min9,
    chroma_cqt_min10 = EXCLUDED.chroma_cqt_min10,
    chroma_cqt_min11 = EXCLUDED.chroma_cqt_min11,
    chroma_cqt_skew = EXCLUDED.chroma_cqt_skew,
    chroma_cqt_skew1 = EXCLUDED.chroma_cqt_skew1,
    chroma_cqt_skew2 = EXCLUDED.chroma_cqt_skew2,
    chroma_cqt_skew3 = EXCLUDED.chroma_cqt_skew3,
    chroma_cqt_skew4 = EXCLUDED.chroma_cqt_skew4,
    chroma_cqt_skew5 = EXCLUDED.chroma_cqt_skew5,
    chroma_cqt_skew6 = EXCLUDED.chroma_cqt_skew6,
    chroma_cqt_skew7 = EXCLUDED.chroma_cqt_skew7,
    chroma_cqt_skew8 = EXCLUDED.chroma_cqt_skew8,
    chroma_cqt_skew9 = EXCLUDED.chroma_cqt_skew9,
    chroma_cqt_skew10 = EXCLUDED.chroma_cqt_skew10,
    chroma_cqt_skew11 = EXCLUDED.chroma_cqt_skew11,
    chroma_cqt_std = EXCLUDED.chroma_cqt_std,
    chroma_cqt_std1 = EXCLUDED.chroma_cqt_std1,
    chroma_cqt_std2 = EXCLUDED.chroma_cqt_std2,
    chroma_cqt_std3 = EXCLUDED.chroma_cqt_std3,
    chroma_cqt_std4 = EXCLUDED.chroma_cqt_std4,
    chroma_cqt_std5 = EXCLUDED.chroma_cqt_std5,
    chroma_cqt_std6 = EXCLUDED.chroma_cqt_std6,
    chroma_cqt_std7 = EXCLUDED.chroma_cqt_std7,
    chroma_cqt_std8 = EXCLUDED.chroma_cqt_std8,
    chroma_cqt_std9 = EXCLUDED.chroma_cqt_std9,
    chroma_cqt_std10 = EXCLUDED.chroma_cqt_std10,
    chroma_cqt_std11 = EXCLUDED.chroma_cqt_std11,
    chroma_stft_kurtosis = EXCLUDED.chroma_stft_kurtosis,
    chroma_stft_kurtosis1 = EXCLUDED.chroma_stft_kurtosis1,
    chroma_stft_kurtosis2 = EXCLUDED.chroma_stft_kurtosis2,
    chroma_stft_kurtosis3 = EXCLUDED.chroma_stft_kurtosis3,
    chroma_stft_kurtosis4 = EXCLUDED.chroma_stft_kurtosis4,
    chroma_stft_kurtosis5 = EXCLUDED.chroma_stft_kurtosis5,
    chroma_stft_kurtosis6 = EXCLUDED.chroma_stft_kurtosis6,
    chroma_stft_kurtosis7 = EXCLUDED.chroma_stft_kurtosis7,
    chroma_stft_kurtosis8 = EXCLUDED.chroma_stft_kurtosis8,
    chroma_stft_kurtosis9 = EXCLUDED.chroma_stft_kurtosis9,
    chroma_stft_kurtosis10 = EXCLUDED.chroma_stft_kurtosis10,
    chroma_stft_kurtosis11 = EXCLUDED.chroma_stft_kurtosis11,
    chroma_stft_max = EXCLUDED.chroma_stft_max,
    chroma_stft_max1 = EXCLUDED.chroma_stft_max1,
    chroma_stft_max2 = EXCLUDED.chroma_stft_max2,
    chroma_stft_max3 = EXCLUDED.chroma_stft_max3,
    chroma_stft_max4 = EXCLUDED.chroma_stft_max4,
    chroma_stft_max5 = EXCLUDED.chroma_stft_max5,
    chroma_stft_max6 = EXCLUDED.chroma_stft_max6,
    chroma_stft_max7 = EXCLUDED.chroma_stft_max7,
    chroma_stft_max8 = EXCLUDED.chroma_stft_max8,
    chroma_stft_max9 = EXCLUDED.chroma_stft_max9,
    chroma_stft_max10 = EXCLUDED.chroma_stft_max10,
    chroma_stft_max11 = EXCLUDED.chroma_stft_max11,
    chroma_stft_mean = EXCLUDED.chroma_stft_mean,
    chroma_stft_mean1 = EXCLUDED.chroma_stft_mean1,
    chroma_stft_mean2 = EXCLUDED.chroma_stft_mean2,
    chroma_stft_mean3 = EXCLUDED.chroma_stft_mean3,
    chroma_stft_mean4 = EXCLUDED.chroma_stft_mean4,
    chroma_stft_mean5 = EXCLUDED.chroma_stft_mean5,
    chroma_stft_mean6 = EXCLUDED.chroma_stft_mean6,
    chroma_stft_mean7 = EXCLUDED.chroma_stft_mean7,
    chroma_stft_mean8 = EXCLUDED.chroma_stft_mean8,
    chroma_stft_mean9 = EXCLUDED.chroma_stft_mean9,
    chroma_stft_mean10 = EXCLUDED.chroma_stft_mean10,
    chroma_stft_mean11 = EXCLUDED.chroma_stft_mean11,
    chroma_stft_median = EXCLUDED.chroma_stft_median,
    chroma_stft_median1 = EXCLUDED.chroma_stft_median1,
    chroma_stft_median2 = EXCLUDED.chroma_stft_median2,
    chroma_stft_median3 = EXCLUDED.chroma_stft_median3,
    chroma_stft_median4 = EXCLUDED.chroma_stft_median4,
    chroma_stft_median5 = EXCLUDED.chroma_stft_median5,
    chroma_stft_median6 = EXCLUDED.chroma_stft_median6,
    chroma_stft_median7 = EXCLUDED.chroma_stft_median7,
    chroma_stft_median8 = EXCLUDED.chroma_stft_median8,
    chroma_stft_median9 = EXCLUDED.chroma_stft_median9,
    chroma_stft_median10 = EXCLUDED.chroma_stft_median10,
    chroma_stft_median11 = EXCLUDED.chroma_stft_median11,
    chroma_stft_min = EXCLUDED.chroma_stft_min,
    chroma_stft_min1 = EXCLUDED.chroma_stft_min1,
    chroma_stft_min2 = EXCLUDED.chroma_stft_min2,
    chroma_stft_min3 = EXCLUDED.chroma_stft_min3,
    chroma_stft_min4 = EXCLUDED.chroma_stft_min4,
    chroma_stft_min5 = EXCLUDED.chroma_stft_min5,
    chroma_stft_min6 = EXCLUDED.chroma_stft_min6,
    chroma_stft_min7 = EXCLUDED.chroma_stft_min7,
    chroma_stft_min8 = EXCLUDED.chroma_stft_min8,
    chroma_stft_min9 = EXCLUDED.chroma_stft_min9,
    chroma_stft_min10 = EXCLUDED.chroma_stft_min10,
    chroma_stft_min11 = EXCLUDED.chroma_stft_min11,
    chroma_stft_skew = EXCLUDED.chroma_stft_skew,
    chroma_stft_skew1 = EXCLUDED.chroma_stft_skew1,
    chroma_stft_skew2 = EXCLUDED.chroma_stft_skew2,
    chroma_stft_skew3 = EXCLUDED.chroma_stft_skew3,
    chroma_stft_skew4 = EXCLUDED.chroma_stft_skew4,
    chroma_stft_skew5 = EXCLUDED.chroma_stft_skew5,
    chroma_stft_skew6 = EXCLUDED.chroma_stft_skew6,
    chroma_stft_skew7 = EXCLUDED.chroma_stft_skew7,
    chroma_stft_skew8 = EXCLUDED.chroma_stft_skew8,
    chroma_stft_skew9 = EXCLUDED.chroma_stft_skew9,
    chroma_stft_skew10 = EXCLUDED.chroma_stft_skew10,
    chroma_stft_skew11 = EXCLUDED.chroma_stft_skew11,
    chroma_stft_std = EXCLUDED.chroma_stft_std,
    chroma_stft_std1 = EXCLUDED.chroma_stft_std1,
    chroma_stft_std2 = EXCLUDED.chroma_stft_std2,
    chroma_stft_std3 = EXCLUDED.chroma_stft_std3,
    chroma_stft_std4 = EXCLUDED.chroma_stft_std4,
    chroma_stft_std5 = EXCLUDED.chroma_stft_std5,
    chroma_stft_std6 = EXCLUDED.chroma_stft_std6,
    chroma_stft_std7 = EXCLUDED.chroma_stft_std7,
    chroma_stft_std8 = EXCLUDED.chroma_stft_std8,
    chroma_stft_std9 = EXCLUDED.chroma_stft_std9,
    chroma_stft_std10 = EXCLUDED.chroma_stft_std10,
    chroma_stft_std11 = EXCLUDED.chroma_stft_std11,
    mfcc_kurtosis = EXCLUDED.mfcc_kurtosis,
    mfcc_kurtosis1 = EXCLUDED.mfcc_kurtosis1,
    mfcc_kurtosis2 = EXCLUDED.mfcc_kurtosis2,
    mfcc_kurtosis3 = EXCLUDED.mfcc_kurtosis3,
    mfcc_kurtosis4 = EXCLUDED.mfcc_kurtosis4,
    mfcc_kurtosis5 = EXCLUDED.mfcc_kurtosis5,
    mfcc_kurtosis6 = EXCLUDED.mfcc_kurtosis6,
    mfcc_kurtosis7 = EXCLUDED.mfcc_kurtosis7,
    mfcc_kurtosis8 = EXCLUDED.mfcc_kurtosis8,
    mfcc_kurtosis9 = EXCLUDED.mfcc_kurtosis9,
    mfcc_kurtosis10 = EXCLUDED.mfcc_kurtosis10,
    mfcc_kurtosis11 = EXCLUDED.mfcc_kurtosis11,
    mfcc_kurtosis12 = EXCLUDED.mfcc_kurtosis12,
    mfcc_kurtosis13 = EXCLUDED.mfcc_kurtosis13,
    mfcc_kurtosis14 = EXCLUDED.mfcc_kurtosis14,
    mfcc_kurtosis15 = EXCLUDED.mfcc_kurtosis15,
    mfcc_kurtosis16 = EXCLUDED.mfcc_kurtosis16,
    mfcc_kurtosis17 = EXCLUDED.mfcc_kurtosis17,
    mfcc_kurtosis18 = EXCLUDED.mfcc_kurtosis18,
    mfcc_kurtosis19 = EXCLUDED.mfcc_kurtosis19,
    mfcc_max = EXCLUDED.mfcc_max,
    mfcc_max1 = EXCLUDED.mfcc_max1,
    mfcc_max2 = EXCLUDED.mfcc_max2,
    mfcc_max3 = EXCLUDED.mfcc_max3,
    mfcc_max4 = EXCLUDED.mfcc_max4,
    mfcc_max5 = EXCLUDED.mfcc_max5,
    mfcc_max6 = EXCLUDED.mfcc_max6,
    mfcc_max7 = EXCLUDED.mfcc_max7,
    mfcc_max8 = EXCLUDED.mfcc_max8,
    mfcc_max9 = EXCLUDED.mfcc_max9,
    mfcc_max10 = EXCLUDED.mfcc_max10,
    mfcc_max11 = EXCLUDED.mfcc_max11,
    mfcc_max12 = EXCLUDED.mfcc_max12,
    mfcc_max13 = EXCLUDED.mfcc_max13,
    mfcc_max14 = EXCLUDED.mfcc_max14,
    mfcc_max15 = EXCLUDED.mfcc_max15,
    mfcc_max16 = EXCLUDED.mfcc_max16,
    mfcc_max17 = EXCLUDED.mfcc_max17,
    mfcc_max18 = EXCLUDED.mfcc_max18,
    mfcc_max19 = EXCLUDED.mfcc_max19,
    mfcc_mean = EXCLUDED.mfcc_mean,
    mfcc_mean1 = EXCLUDED.mfcc_mean1,
    mfcc_mean2 = EXCLUDED.mfcc_mean2,
    mfcc_mean3 = EXCLUDED.mfcc_mean3,
    mfcc_mean4 = EXCLUDED.mfcc_mean4,
    mfcc_mean5 = EXCLUDED.mfcc_mean5,
    mfcc_mean6 = EXCLUDED.mfcc_mean6,
    mfcc_mean7 = EXCLUDED.mfcc_mean7,
    mfcc_mean8 = EXCLUDED.mfcc_mean8,
    mfcc_mean9 = EXCLUDED.mfcc_mean9,
    mfcc_mean10 = EXCLUDED.mfcc_mean10,
    mfcc_mean11 = EXCLUDED.mfcc_mean11,
    mfcc_mean12 = EXCLUDED.mfcc_mean12,
    mfcc_mean13 = EXCLUDED.mfcc_mean13,
    mfcc_mean14 = EXCLUDED.mfcc_mean14,
    mfcc_mean15 = EXCLUDED.mfcc_mean15,
    mfcc_mean16 = EXCLUDED.mfcc_mean16,
    mfcc_mean17 = EXCLUDED.mfcc_mean17,
    mfcc_mean18 = EXCLUDED.mfcc_mean18,
    mfcc_mean19 = EXCLUDED.mfcc_mean19,
    mfcc_median = EXCLUDED.mfcc_median,
    mfcc_median1 = EXCLUDED.mfcc_median1,
    mfcc_median2 = EXCLUDED.mfcc_median2,
    mfcc_median3 = EXCLUDED.mfcc_median3,
    mfcc_median4 = EXCLUDED.mfcc_median4,
    mfcc_median5 = EXCLUDED.mfcc_median5,
    mfcc_median6 = EXCLUDED.mfcc_median6,
    mfcc_median7 = EXCLUDED.mfcc_median7,
    mfcc_median8 = EXCLUDED.mfcc_median8,
    mfcc_median9 = EXCLUDED.mfcc_median9,
    mfcc_median10 = EXCLUDED.mfcc_median10,
    mfcc_median11 = EXCLUDED.mfcc_median11,
    mfcc_median12 = EXCLUDED.mfcc_median12,
    mfcc_median13 = EXCLUDED.mfcc_median13,
    mfcc_median14 = EXCLUDED.mfcc_median14,
    mfcc_median15 = EXCLUDED.mfcc_median15,
    mfcc_median16 = EXCLUDED.mfcc_median16,
    mfcc_median17 = EXCLUDED.mfcc_median17,
    mfcc_median18 = EXCLUDED.mfcc_median18,
    mfcc_median19 = EXCLUDED.mfcc_median19,
    mfcc_min = EXCLUDED.mfcc_min,
    mfcc_min1 = EXCLUDED.mfcc_min1,
    mfcc_min2 = EXCLUDED.mfcc_min2,
    mfcc_min3 = EXCLUDED.mfcc_min3,
    mfcc_min4 = EXCLUDED.mfcc_min4,
    mfcc_min5 = EXCLUDED.mfcc_min5,
    mfcc_min6 = EXCLUDED.mfcc_min6,
    mfcc_min7 = EXCLUDED.mfcc_min7,
    mfcc_min8 = EXCLUDED.mfcc_min8,
    mfcc_min9 = EXCLUDED.mfcc_min9,
    mfcc_min10 = EXCLUDED.mfcc_min10,
    mfcc_min11 = EXCLUDED.mfcc_min11,
    mfcc_min12 = EXCLUDED.mfcc_min12,
    mfcc_min13 = EXCLUDED.mfcc_min13,
    mfcc_min14 = EXCLUDED.mfcc_min14,
    mfcc_min15 = EXCLUDED.mfcc_min15,
    mfcc_min16 = EXCLUDED.mfcc_min16,
    mfcc_min17 = EXCLUDED.mfcc_min17,
    mfcc_min18 = EXCLUDED.mfcc_min18,
    mfcc_min19 = EXCLUDED.mfcc_min19,
    mfcc_skew = EXCLUDED.mfcc_skew,
    mfcc_skew1 = EXCLUDED.mfcc_skew1,
    mfcc_skew2 = EXCLUDED.mfcc_skew2,
    mfcc_skew3 = EXCLUDED.mfcc_skew3,
    mfcc_skew4 = EXCLUDED.mfcc_skew4,
    mfcc_skew5 = EXCLUDED.mfcc_skew5,
    mfcc_skew6 = EXCLUDED.mfcc_skew6,
    mfcc_skew7 = EXCLUDED.mfcc_skew7,
    mfcc_skew8 = EXCLUDED.mfcc_skew8,
    mfcc_skew9 = EXCLUDED.mfcc_skew9,
    mfcc_skew10 = EXCLUDED.mfcc_skew10,
    mfcc_skew11 = EXCLUDED.mfcc_skew11,
    mfcc_skew12 = EXCLUDED.mfcc_skew12,
    mfcc_skew13 = EXCLUDED.mfcc_skew13,
    mfcc_skew14 = EXCLUDED.mfcc_skew14,
    mfcc_skew15 = EXCLUDED.mfcc_skew15,
    mfcc_skew16 = EXCLUDED.mfcc_skew16,
    mfcc_skew17 = EXCLUDED.mfcc_skew17,
    mfcc_skew18 = EXCLUDED.mfcc_skew18,
    mfcc_skew19 = EXCLUDED.mfcc_skew19,
    mfcc_std = EXCLUDED.mfcc_std,
    mfcc_std1 = EXCLUDED.mfcc_std1,
    mfcc_std2 = EXCLUDED.mfcc_std2,
    mfcc_std3 = EXCLUDED.mfcc_std3,
    mfcc_std4 = EXCLUDED.mfcc_std4,
    mfcc_std5 = EXCLUDED.mfcc_std5,
    mfcc_std6 = EXCLUDED.mfcc_std6,
    mfcc_std7 = EXCLUDED.mfcc_std7,
    mfcc_std8 = EXCLUDED.mfcc_std8,
    mfcc_std9 = EXCLUDED.mfcc_std9,
    mfcc_std10 = EXCLUDED.mfcc_std10,
    mfcc_std11 = EXCLUDED.mfcc_std11,
    mfcc_std12 = EXCLUDED.mfcc_std12,
    mfcc_std13 = EXCLUDED.mfcc_std13,
    mfcc_std14 = EXCLUDED.mfcc_std14,
    mfcc_std15 = EXCLUDED.mfcc_std15,
    mfcc_std16 = EXCLUDED.mfcc_std16,
    mfcc_std17 = EXCLUDED.mfcc_std17,
    mfcc_std18 = EXCLUDED.mfcc_std18,
    mfcc_std19 = EXCLUDED.mfcc_std19,
    rmse_kurtosis = EXCLUDED.rmse_kurtosis,
    rmse_max = EXCLUDED.rmse_max,
    rmse_mean = EXCLUDED.rmse_mean,
    rmse_median = EXCLUDED.rmse_median,
    rmse_min = EXCLUDED.rmse_min,
    rmse_skew = EXCLUDED.rmse_skew,
    rmse_std = EXCLUDED.rmse_std,
    spectral_bandwidth_kurtosis = EXCLUDED.spectral_bandwidth_kurtosis,
    spectral_bandwidth_max = EXCLUDED.spectral_bandwidth_max,
    spectral_bandwidth_mean = EXCLUDED.spectral_bandwidth_mean,
    spectral_bandwidth_median = EXCLUDED.spectral_bandwidth_median,
    spectral_bandwidth_min = EXCLUDED.spectral_bandwidth_min,
    spectral_bandwidth_skew = EXCLUDED.spectral_bandwidth_skew,
    spectral_bandwidth_std = EXCLUDED.spectral_bandwidth_std,
    spectral_centroid_kurtosis = EXCLUDED.spectral_centroid_kurtosis,
    spectral_centroid_max = EXCLUDED.spectral_centroid_max,
    spectral_centroid_mean = EXCLUDED.spectral_centroid_mean,
    spectral_centroid_median = EXCLUDED.spectral_centroid_median,
    spectral_centroid_min = EXCLUDED.spectral_centroid_min,
    spectral_centroid_skew = EXCLUDED.spectral_centroid_skew,
    spectral_centroid_std = EXCLUDED.spectral_centroid_std,
    spectral_contrast_kurtosis = EXCLUDED.spectral_contrast_kurtosis,
    spectral_contrast_kurtosis1 = EXCLUDED.spectral_contrast_kurtosis1,
    spectral_contrast_kurtosis2 = EXCLUDED.spectral_contrast_kurtosis2,
    spectral_contrast_kurtosis3 = EXCLUDED.spectral_contrast_kurtosis3,
    spectral_contrast_kurtosis4 = EXCLUDED.spectral_contrast_kurtosis4,
    spectral_contrast_kurtosis5 = EXCLUDED.spectral_contrast_kurtosis5,
    spectral_contrast_kurtosis6 = EXCLUDED.spectral_contrast_kurtosis6,
    spectral_contrast_max = EXCLUDED.spectral_contrast_max,
    spectral_contrast_max1 = EXCLUDED.spectral_contrast_max1,
    spectral_contrast_max2 = EXCLUDED.spectral_contrast_max2,
    spectral_contrast_max3 = EXCLUDED.spectral_contrast_max3,
    spectral_contrast_max4 = EXCLUDED.spectral_contrast_max4,
    spectral_contrast_max5 = EXCLUDED.spectral_contrast_max5,
    spectral_contrast_max6 = EXCLUDED.spectral_contrast_max6,
    spectral_contrast_mean = EXCLUDED.spectral_contrast_mean,
    spectral_contrast_mean1 = EXCLUDED.spectral_contrast_mean1,
    spectral_contrast_mean2 = EXCLUDED.spectral_contrast_mean2,
    spectral_contrast_mean3 = EXCLUDED.spectral_contrast_mean3,
    spectral_contrast_mean4 = EXCLUDED.spectral_contrast_mean4,
    spectral_contrast_mean5 = EXCLUDED.spectral_contrast_mean5,
    spectral_contrast_mean6 = EXCLUDED.spectral_contrast_mean6,
    spectral_contrast_median = EXCLUDED.spectral_contrast_median,
    spectral_contrast_median1 = EXCLUDED.spectral_contrast_median1,
    spectral_contrast_median2 = EXCLUDED.spectral_contrast_median2,
    spectral_contrast_median3 = EXCLUDED.spectral_contrast_median3,
    spectral_contrast_median4 = EXCLUDED.spectral_contrast_median4,
    spectral_contrast_median5 = EXCLUDED.spectral_contrast_median5,
    spectral_contrast_median6 = EXCLUDED.spectral_contrast_median6,
    spectral_contrast_min = EXCLUDED.spectral_contrast_min,
    spectral_contrast_min1 = EXCLUDED.spectral_contrast_min1,
    spectral_contrast_min2 = EXCLUDED.spectral_contrast_min2,
    spectral_contrast_min3 = EXCLUDED.spectral_contrast_min3,
    spectral_contrast_min4 = EXCLUDED.spectral_contrast_min4,
    spectral_contrast_min5 = EXCLUDED.spectral_contrast_min5,
    spectral_contrast_min6 = EXCLUDED.spectral_contrast_min6,
    spectral_contrast_skew = EXCLUDED.spectral_contrast_skew,
    spectral_contrast_skew1 = EXCLUDED.spectral_contrast_skew1,
    spectral_contrast_skew2 = EXCLUDED.spectral_contrast_skew2,
    spectral_contrast_skew3 = EXCLUDED.spectral_contrast_skew3,
    spectral_contrast_skew4 = EXCLUDED.spectral_contrast_skew4,
    spectral_contrast_skew5 = EXCLUDED.spectral_contrast_skew5,
    spectral_contrast_skew6 = EXCLUDED.spectral_contrast_skew6,
    spectral_contrast_std = EXCLUDED.spectral_contrast_std,
    spectral_contrast_std1 = EXCLUDED.spectral_contrast_std1,
    spectral_contrast_std2 = EXCLUDED.spectral_contrast_std2,
    spectral_contrast_std3 = EXCLUDED.spectral_contrast_std3,
    spectral_contrast_std4 = EXCLUDED.spectral_contrast_std4,
    spectral_contrast_std5 = EXCLUDED.spectral_contrast_std5,
    spectral_contrast_std6 = EXCLUDED.spectral_contrast_std6,
    spectral_rolloff_kurtosis = EXCLUDED.spectral_rolloff_kurtosis,
    spectral_rolloff_max = EXCLUDED.spectral_rolloff_max,
    spectral_rolloff_mean = EXCLUDED.spectral_rolloff_mean,
    spectral_rolloff_median = EXCLUDED.spectral_rolloff_median,
    spectral_rolloff_min = EXCLUDED.spectral_rolloff_min,
    spectral_rolloff_skew = EXCLUDED.spectral_rolloff_skew,
    spectral_rolloff_std = EXCLUDED.spectral_rolloff_std,
    tonnetz_kurtosis = EXCLUDED.tonnetz_kurtosis,
    tonnetz_kurtosis1 = EXCLUDED.tonnetz_kurtosis1,
    tonnetz_kurtosis2 = EXCLUDED.tonnetz_kurtosis2,
    tonnetz_kurtosis3 = EXCLUDED.tonnetz_kurtosis3,
    tonnetz_kurtosis4 = EXCLUDED.tonnetz_kurtosis4,
    tonnetz_kurtosis5 = EXCLUDED.tonnetz_kurtosis5,
    tonnetz_max = EXCLUDED.tonnetz_max,
    tonnetz_max1 = EXCLUDED.tonnetz_max1,
    tonnetz_max2 = EXCLUDED.tonnetz_max2,
    tonnetz_max3 = EXCLUDED.tonnetz_max3,
    tonnetz_max4 = EXCLUDED.tonnetz_max4,
    tonnetz_max5 = EXCLUDED.tonnetz_max5,
    tonnetz_mean = EXCLUDED.tonnetz_mean,
    tonnetz_mean1 = EXCLUDED.tonnetz_mean1,
    tonnetz_mean2 = EXCLUDED.tonnetz_mean2,
    tonnetz_mean3 = EXCLUDED.tonnetz_mean3,
    tonnetz_mean4 = EXCLUDED.tonnetz_mean4,
    tonnetz_mean5 = EXCLUDED.tonnetz_mean5,
    tonnetz_median = EXCLUDED.tonnetz_median,
    tonnetz_median1 = EXCLUDED.tonnetz_median1,
    tonnetz_median2 = EXCLUDED.tonnetz_median2,
    tonnetz_median3 = EXCLUDED.tonnetz_median3,
    tonnetz_median4 = EXCLUDED.tonnetz_median4,
    tonnetz_median5 = EXCLUDED.tonnetz_median5,
    tonnetz_min = EXCLUDED.tonnetz_min,
    tonnetz_min1 = EXCLUDED.tonnetz_min1,
    tonnetz_min2 = EXCLUDED.tonnetz_min2,
    tonnetz_min3 = EXCLUDED.tonnetz_min3,
    tonnetz_min4 = EXCLUDED.tonnetz_min4,
    tonnetz_min5 = EXCLUDED.tonnetz_min5,
    tonnetz_skew = EXCLUDED.tonnetz_skew,
    tonnetz_skew1 = EXCLUDED.tonnetz_skew1,
    tonnetz_skew2 = EXCLUDED.tonnetz_skew2,
    tonnetz_skew3 = EXCLUDED.tonnetz_skew3,
    tonnetz_skew4 = EXCLUDED.tonnetz_skew4,
    tonnetz_skew5 = EXCLUDED.tonnetz_skew5,
    tonnetz_std = EXCLUDED.tonnetz_std,
    tonnetz_std1 = EXCLUDED.tonnetz_std1,
    tonnetz_std2 = EXCLUDED.tonnetz_std2,
    tonnetz_std3 = EXCLUDED.tonnetz_std3,
    tonnetz_std4 = EXCLUDED.tonnetz_std4,
    tonnetz_std5 = EXCLUDED.tonnetz_std5,
    zcr_kurtosis = EXCLUDED.zcr_kurtosis,
    zcr_max = EXCLUDED.zcr_max,
    zcr_mean = EXCLUDED.zcr_mean,
    zcr_median = EXCLUDED.zcr_median,
    zcr_min = EXCLUDED.zcr_min,
    zcr_skew = EXCLUDED.zcr_skew,
    zcr_std = EXCLUDED.zcr_std
;

DROP TABLE stg_features;

-- ====================================================================================
-- USERS (clean_answers.csv)
-- ====================================================================================
CREATE TEMP TABLE stg_user (
    created_at TIMESTAMP,
    has_consented TEXT,
    is_listening TEXT,
    frequency TEXT,
    context TEXT,
    "when" DOUBLE PRECISION,
    how TEXT,
    platform TEXT,
    utility TEXT,
    track_genre TEXT,
    duration DOUBLE PRECISION,
    energy TEXT,
    tempo DOUBLE PRECISION,
    feeling TEXT,
    is_live TEXT,
    quality DOUBLE PRECISION,
    curiosity DOUBLE PRECISION,
    age_range TEXT,
    gender TEXT,
    position TEXT,
    account_uuid UUID DEFAULT uuid_generate_v4()
);

\copy stg_user (created_at, has_consented, is_listening, frequency, context, "when", how, platform, utility, track_genre, duration, energy, tempo, feeling, is_live, quality, curiosity, age_range, gender, position) FROM 'T1_alternants/src/clean/out/clean_answers.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');

-- Insert Accounts
INSERT INTO account (account_id, login, name, email, created_at)
SELECT 
    account_uuid,
    'user_' || substr(account_uuid::text, 1, 8),
    'User ' || substr(account_uuid::text, 1, 8),
    'user_' || substr(account_uuid::text, 1, 8) || '@test.com',
    created_at
FROM stg_user;

-- Insert Users
INSERT INTO "user" (account_id, pseudo)
SELECT 
    account_uuid,
    'User_' || substr(account_uuid::text, 1, 8)
FROM stg_user;

-- Insert Preferences
INSERT INTO preference (
    account_id, age_range, gender, position, has_consented, is_listening,
    frequency, when_listening, duration_pref, energy_pref, tempo_pref,
    feeling_pref, is_live_pref, quality_pref, curiosity_pref, context,
    how, platform, utility
)
SELECT
    account_uuid, age_range, gender, position, 
    (has_consented IS NOT NULL)::boolean, 
    (is_listening = 'True')::boolean,
    frequency, "when", CAST(duration AS INT), energy, tempo,
    feeling, is_live, CAST(quality AS INT), CAST(curiosity AS INT), context,
    how, platform, utility
FROM stg_user;

-- Genre Preference
-- CSV: track_genre = "['pop', 'rap']"
WITH user_genres AS (
    SELECT 
        account_uuid,
        trim(genre_name) as genre_name
    FROM stg_user, unnest(parse_python_list(track_genre)) as genre_name
)
INSERT INTO genre_preference (account_id, genre_id)
SELECT 
    ug.account_uuid,
    g.genre_id
FROM user_genres ug
JOIN genre g ON lower(g.title) = lower(ug.genre_name)
ON CONFLICT DO NOTHING;

-- Cleanup
DROP TABLE stg_genre;
DROP TABLE stg_artist;
DROP TABLE stg_album;
DROP TABLE stg_track;
DROP TABLE stg_tags;
DROP TABLE stg_echonest;
DROP TABLE stg_user;
DROP TABLE _legacy_id_map;

-- End
