-- ====================================================================================
-- CARACTERISTIQUES TEMPORELLES
-- ====================================================================================
CREATE TEMP TABLE stg_features (
    track_id TEXT,
    chroma_cens_kurtosis DOUBLE PRECISION,
    "chroma_cens_kurtosis.1" DOUBLE PRECISION,
    "chroma_cens_kurtosis.2" DOUBLE PRECISION,
    "chroma_cens_kurtosis.3" DOUBLE PRECISION,
    "chroma_cens_kurtosis.4" DOUBLE PRECISION,
    "chroma_cens_kurtosis.5" DOUBLE PRECISION,
    "chroma_cens_kurtosis.6" DOUBLE PRECISION,
    "chroma_cens_kurtosis.7" DOUBLE PRECISION,
    "chroma_cens_kurtosis.8" DOUBLE PRECISION,
    "chroma_cens_kurtosis.9" DOUBLE PRECISION,
    "chroma_cens_kurtosis.10" DOUBLE PRECISION,
    "chroma_cens_kurtosis.11" DOUBLE PRECISION,
    chroma_cens_max DOUBLE PRECISION,
    "chroma_cens_max.1" DOUBLE PRECISION,
    "chroma_cens_max.2" DOUBLE PRECISION,
    "chroma_cens_max.3" DOUBLE PRECISION,
    "chroma_cens_max.4" DOUBLE PRECISION,
    "chroma_cens_max.5" DOUBLE PRECISION,
    "chroma_cens_max.6" DOUBLE PRECISION,
    "chroma_cens_max.7" DOUBLE PRECISION,
    "chroma_cens_max.8" DOUBLE PRECISION,
    "chroma_cens_max.9" DOUBLE PRECISION,
    "chroma_cens_max.10" DOUBLE PRECISION,
    "chroma_cens_max.11" DOUBLE PRECISION,
    chroma_cens_mean DOUBLE PRECISION,
    "chroma_cens_mean.1" DOUBLE PRECISION,
    "chroma_cens_mean.2" DOUBLE PRECISION,
    "chroma_cens_mean.3" DOUBLE PRECISION,
    "chroma_cens_mean.4" DOUBLE PRECISION,
    "chroma_cens_mean.5" DOUBLE PRECISION,
    "chroma_cens_mean.6" DOUBLE PRECISION,
    "chroma_cens_mean.7" DOUBLE PRECISION,
    "chroma_cens_mean.8" DOUBLE PRECISION,
    "chroma_cens_mean.9" DOUBLE PRECISION,
    "chroma_cens_mean.10" DOUBLE PRECISION,
    "chroma_cens_mean.11" DOUBLE PRECISION,
    chroma_cens_median DOUBLE PRECISION,
    "chroma_cens_median.1" DOUBLE PRECISION,
    "chroma_cens_median.2" DOUBLE PRECISION,
    "chroma_cens_median.3" DOUBLE PRECISION,
    "chroma_cens_median.4" DOUBLE PRECISION,
    "chroma_cens_median.5" DOUBLE PRECISION,
    "chroma_cens_median.6" DOUBLE PRECISION,
    "chroma_cens_median.7" DOUBLE PRECISION,
    "chroma_cens_median.8" DOUBLE PRECISION,
    "chroma_cens_median.9" DOUBLE PRECISION,
    "chroma_cens_median.10" DOUBLE PRECISION,
    "chroma_cens_median.11" DOUBLE PRECISION,
    chroma_cens_min DOUBLE PRECISION,
    "chroma_cens_min.1" DOUBLE PRECISION,
    "chroma_cens_min.2" DOUBLE PRECISION,
    "chroma_cens_min.3" DOUBLE PRECISION,
    "chroma_cens_min.4" DOUBLE PRECISION,
    "chroma_cens_min.5" DOUBLE PRECISION,
    "chroma_cens_min.6" DOUBLE PRECISION,
    "chroma_cens_min.7" DOUBLE PRECISION,
    "chroma_cens_min.8" DOUBLE PRECISION,
    "chroma_cens_min.9" DOUBLE PRECISION,
    "chroma_cens_min.10" DOUBLE PRECISION,
    "chroma_cens_min.11" DOUBLE PRECISION,
    chroma_cens_skew DOUBLE PRECISION,
    "chroma_cens_skew.1" DOUBLE PRECISION,
    "chroma_cens_skew.2" DOUBLE PRECISION,
    "chroma_cens_skew.3" DOUBLE PRECISION,
    "chroma_cens_skew.4" DOUBLE PRECISION,
    "chroma_cens_skew.5" DOUBLE PRECISION,
    "chroma_cens_skew.6" DOUBLE PRECISION,
    "chroma_cens_skew.7" DOUBLE PRECISION,
    "chroma_cens_skew.8" DOUBLE PRECISION,
    "chroma_cens_skew.9" DOUBLE PRECISION,
    "chroma_cens_skew.10" DOUBLE PRECISION,
    "chroma_cens_skew.11" DOUBLE PRECISION,
    chroma_cens_std DOUBLE PRECISION,
    "chroma_cens_std.1" DOUBLE PRECISION,
    "chroma_cens_std.2" DOUBLE PRECISION,
    "chroma_cens_std.3" DOUBLE PRECISION,
    "chroma_cens_std.4" DOUBLE PRECISION,
    "chroma_cens_std.5" DOUBLE PRECISION,
    "chroma_cens_std.6" DOUBLE PRECISION,
    "chroma_cens_std.7" DOUBLE PRECISION,
    "chroma_cens_std.8" DOUBLE PRECISION,
    "chroma_cens_std.9" DOUBLE PRECISION,
    "chroma_cens_std.10" DOUBLE PRECISION,
    "chroma_cens_std.11" DOUBLE PRECISION,
    chroma_cqt_kurtosis DOUBLE PRECISION,
    "chroma_cqt_kurtosis.1" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.2" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.3" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.4" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.5" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.6" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.7" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.8" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.9" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.10" DOUBLE PRECISION,
    "chroma_cqt_kurtosis.11" DOUBLE PRECISION,
    chroma_cqt_max DOUBLE PRECISION,
    "chroma_cqt_max.1" DOUBLE PRECISION,
    "chroma_cqt_max.2" DOUBLE PRECISION,
    "chroma_cqt_max.3" DOUBLE PRECISION,
    "chroma_cqt_max.4" DOUBLE PRECISION,
    "chroma_cqt_max.5" DOUBLE PRECISION,
    "chroma_cqt_max.6" DOUBLE PRECISION,
    "chroma_cqt_max.7" DOUBLE PRECISION,
    "chroma_cqt_max.8" DOUBLE PRECISION,
    "chroma_cqt_max.9" DOUBLE PRECISION,
    "chroma_cqt_max.10" DOUBLE PRECISION,
    "chroma_cqt_max.11" DOUBLE PRECISION,
    chroma_cqt_mean DOUBLE PRECISION,
    "chroma_cqt_mean.1" DOUBLE PRECISION,
    "chroma_cqt_mean.2" DOUBLE PRECISION,
    "chroma_cqt_mean.3" DOUBLE PRECISION,
    "chroma_cqt_mean.4" DOUBLE PRECISION,
    "chroma_cqt_mean.5" DOUBLE PRECISION,
    "chroma_cqt_mean.6" DOUBLE PRECISION,
    "chroma_cqt_mean.7" DOUBLE PRECISION,
    "chroma_cqt_mean.8" DOUBLE PRECISION,
    "chroma_cqt_mean.9" DOUBLE PRECISION,
    "chroma_cqt_mean.10" DOUBLE PRECISION,
    "chroma_cqt_mean.11" DOUBLE PRECISION,
    chroma_cqt_median DOUBLE PRECISION,
    "chroma_cqt_median.1" DOUBLE PRECISION,
    "chroma_cqt_median.2" DOUBLE PRECISION,
    "chroma_cqt_median.3" DOUBLE PRECISION,
    "chroma_cqt_median.4" DOUBLE PRECISION,
    "chroma_cqt_median.5" DOUBLE PRECISION,
    "chroma_cqt_median.6" DOUBLE PRECISION,
    "chroma_cqt_median.7" DOUBLE PRECISION,
    "chroma_cqt_median.8" DOUBLE PRECISION,
    "chroma_cqt_median.9" DOUBLE PRECISION,
    "chroma_cqt_median.10" DOUBLE PRECISION,
    "chroma_cqt_median.11" DOUBLE PRECISION,
    chroma_cqt_min DOUBLE PRECISION,
    "chroma_cqt_min.1" DOUBLE PRECISION,
    "chroma_cqt_min.2" DOUBLE PRECISION,
    "chroma_cqt_min.3" DOUBLE PRECISION,
    "chroma_cqt_min.4" DOUBLE PRECISION,
    "chroma_cqt_min.5" DOUBLE PRECISION,
    "chroma_cqt_min.6" DOUBLE PRECISION,
    "chroma_cqt_min.7" DOUBLE PRECISION,
    "chroma_cqt_min.8" DOUBLE PRECISION,
    "chroma_cqt_min.9" DOUBLE PRECISION,
    "chroma_cqt_min.10" DOUBLE PRECISION,
    "chroma_cqt_min.11" DOUBLE PRECISION,
    chroma_cqt_skew DOUBLE PRECISION,
    "chroma_cqt_skew.1" DOUBLE PRECISION,
    "chroma_cqt_skew.2" DOUBLE PRECISION,
    "chroma_cqt_skew.3" DOUBLE PRECISION,
    "chroma_cqt_skew.4" DOUBLE PRECISION,
    "chroma_cqt_skew.5" DOUBLE PRECISION,
    "chroma_cqt_skew.6" DOUBLE PRECISION,
    "chroma_cqt_skew.7" DOUBLE PRECISION,
    "chroma_cqt_skew.8" DOUBLE PRECISION,
    "chroma_cqt_skew.9" DOUBLE PRECISION,
    "chroma_cqt_skew.10" DOUBLE PRECISION,
    "chroma_cqt_skew.11" DOUBLE PRECISION,
    chroma_cqt_std DOUBLE PRECISION,
    "chroma_cqt_std.1" DOUBLE PRECISION,
    "chroma_cqt_std.2" DOUBLE PRECISION,
    "chroma_cqt_std.3" DOUBLE PRECISION,
    "chroma_cqt_std.4" DOUBLE PRECISION,
    "chroma_cqt_std.5" DOUBLE PRECISION,
    "chroma_cqt_std.6" DOUBLE PRECISION,
    "chroma_cqt_std.7" DOUBLE PRECISION,
    "chroma_cqt_std.8" DOUBLE PRECISION,
    "chroma_cqt_std.9" DOUBLE PRECISION,
    "chroma_cqt_std.10" DOUBLE PRECISION,
    "chroma_cqt_std.11" DOUBLE PRECISION,
    chroma_stft_kurtosis DOUBLE PRECISION,
    "chroma_stft_kurtosis.1" DOUBLE PRECISION,
    "chroma_stft_kurtosis.2" DOUBLE PRECISION,
    "chroma_stft_kurtosis.3" DOUBLE PRECISION,
    "chroma_stft_kurtosis.4" DOUBLE PRECISION,
    "chroma_stft_kurtosis.5" DOUBLE PRECISION,
    "chroma_stft_kurtosis.6" DOUBLE PRECISION,
    "chroma_stft_kurtosis.7" DOUBLE PRECISION,
    "chroma_stft_kurtosis.8" DOUBLE PRECISION,
    "chroma_stft_kurtosis.9" DOUBLE PRECISION,
    "chroma_stft_kurtosis.10" DOUBLE PRECISION,
    "chroma_stft_kurtosis.11" DOUBLE PRECISION,
    chroma_stft_max DOUBLE PRECISION,
    "chroma_stft_max.1" DOUBLE PRECISION,
    "chroma_stft_max.2" DOUBLE PRECISION,
    "chroma_stft_max.3" DOUBLE PRECISION,
    "chroma_stft_max.4" DOUBLE PRECISION,
    "chroma_stft_max.5" DOUBLE PRECISION,
    "chroma_stft_max.6" DOUBLE PRECISION,
    "chroma_stft_max.7" DOUBLE PRECISION,
    "chroma_stft_max.8" DOUBLE PRECISION,
    "chroma_stft_max.9" DOUBLE PRECISION,
    "chroma_stft_max.10" DOUBLE PRECISION,
    "chroma_stft_max.11" DOUBLE PRECISION,
    chroma_stft_mean DOUBLE PRECISION,
    "chroma_stft_mean.1" DOUBLE PRECISION,
    "chroma_stft_mean.2" DOUBLE PRECISION,
    "chroma_stft_mean.3" DOUBLE PRECISION,
    "chroma_stft_mean.4" DOUBLE PRECISION,
    "chroma_stft_mean.5" DOUBLE PRECISION,
    "chroma_stft_mean.6" DOUBLE PRECISION,
    "chroma_stft_mean.7" DOUBLE PRECISION,
    "chroma_stft_mean.8" DOUBLE PRECISION,
    "chroma_stft_mean.9" DOUBLE PRECISION,
    "chroma_stft_mean.10" DOUBLE PRECISION,
    "chroma_stft_mean.11" DOUBLE PRECISION,
    chroma_stft_median DOUBLE PRECISION,
    "chroma_stft_median.1" DOUBLE PRECISION,
    "chroma_stft_median.2" DOUBLE PRECISION,
    "chroma_stft_median.3" DOUBLE PRECISION,
    "chroma_stft_median.4" DOUBLE PRECISION,
    "chroma_stft_median.5" DOUBLE PRECISION,
    "chroma_stft_median.6" DOUBLE PRECISION,
    "chroma_stft_median.7" DOUBLE PRECISION,
    "chroma_stft_median.8" DOUBLE PRECISION,
    "chroma_stft_median.9" DOUBLE PRECISION,
    "chroma_stft_median.10" DOUBLE PRECISION,
    "chroma_stft_median.11" DOUBLE PRECISION,
    chroma_stft_min DOUBLE PRECISION,
    "chroma_stft_min.1" DOUBLE PRECISION,
    "chroma_stft_min.2" DOUBLE PRECISION,
    "chroma_stft_min.3" DOUBLE PRECISION,
    "chroma_stft_min.4" DOUBLE PRECISION,
    "chroma_stft_min.5" DOUBLE PRECISION,
    "chroma_stft_min.6" DOUBLE PRECISION,
    "chroma_stft_min.7" DOUBLE PRECISION,
    "chroma_stft_min.8" DOUBLE PRECISION,
    "chroma_stft_min.9" DOUBLE PRECISION,
    "chroma_stft_min.10" DOUBLE PRECISION,
    "chroma_stft_min.11" DOUBLE PRECISION,
    chroma_stft_skew DOUBLE PRECISION,
    "chroma_stft_skew.1" DOUBLE PRECISION,
    "chroma_stft_skew.2" DOUBLE PRECISION,
    "chroma_stft_skew.3" DOUBLE PRECISION,
    "chroma_stft_skew.4" DOUBLE PRECISION,
    "chroma_stft_skew.5" DOUBLE PRECISION,
    "chroma_stft_skew.6" DOUBLE PRECISION,
    "chroma_stft_skew.7" DOUBLE PRECISION,
    "chroma_stft_skew.8" DOUBLE PRECISION,
    "chroma_stft_skew.9" DOUBLE PRECISION,
    "chroma_stft_skew.10" DOUBLE PRECISION,
    "chroma_stft_skew.11" DOUBLE PRECISION,
    chroma_stft_std DOUBLE PRECISION,
    "chroma_stft_std.1" DOUBLE PRECISION,
    "chroma_stft_std.2" DOUBLE PRECISION,
    "chroma_stft_std.3" DOUBLE PRECISION,
    "chroma_stft_std.4" DOUBLE PRECISION,
    "chroma_stft_std.5" DOUBLE PRECISION,
    "chroma_stft_std.6" DOUBLE PRECISION,
    "chroma_stft_std.7" DOUBLE PRECISION,
    "chroma_stft_std.8" DOUBLE PRECISION,
    "chroma_stft_std.9" DOUBLE PRECISION,
    "chroma_stft_std.10" DOUBLE PRECISION,
    "chroma_stft_std.11" DOUBLE PRECISION,
    mfcc_kurtosis DOUBLE PRECISION,
    "mfcc_kurtosis.1" DOUBLE PRECISION,
    "mfcc_kurtosis.2" DOUBLE PRECISION,
    "mfcc_kurtosis.3" DOUBLE PRECISION,
    "mfcc_kurtosis.4" DOUBLE PRECISION,
    "mfcc_kurtosis.5" DOUBLE PRECISION,
    "mfcc_kurtosis.6" DOUBLE PRECISION,
    "mfcc_kurtosis.7" DOUBLE PRECISION,
    "mfcc_kurtosis.8" DOUBLE PRECISION,
    "mfcc_kurtosis.9" DOUBLE PRECISION,
    "mfcc_kurtosis.10" DOUBLE PRECISION,
    "mfcc_kurtosis.11" DOUBLE PRECISION,
    "mfcc_kurtosis.12" DOUBLE PRECISION,
    "mfcc_kurtosis.13" DOUBLE PRECISION,
    "mfcc_kurtosis.14" DOUBLE PRECISION,
    "mfcc_kurtosis.15" DOUBLE PRECISION,
    "mfcc_kurtosis.16" DOUBLE PRECISION,
    "mfcc_kurtosis.17" DOUBLE PRECISION,
    "mfcc_kurtosis.18" DOUBLE PRECISION,
    "mfcc_kurtosis.19" DOUBLE PRECISION,
    mfcc_max DOUBLE PRECISION,
    "mfcc_max.1" DOUBLE PRECISION,
    "mfcc_max.2" DOUBLE PRECISION,
    "mfcc_max.3" DOUBLE PRECISION,
    "mfcc_max.4" DOUBLE PRECISION,
    "mfcc_max.5" DOUBLE PRECISION,
    "mfcc_max.6" DOUBLE PRECISION,
    "mfcc_max.7" DOUBLE PRECISION,
    "mfcc_max.8" DOUBLE PRECISION,
    "mfcc_max.9" DOUBLE PRECISION,
    "mfcc_max.10" DOUBLE PRECISION,
    "mfcc_max.11" DOUBLE PRECISION,
    "mfcc_max.12" DOUBLE PRECISION,
    "mfcc_max.13" DOUBLE PRECISION,
    "mfcc_max.14" DOUBLE PRECISION,
    "mfcc_max.15" DOUBLE PRECISION,
    "mfcc_max.16" DOUBLE PRECISION,
    "mfcc_max.17" DOUBLE PRECISION,
    "mfcc_max.18" DOUBLE PRECISION,
    "mfcc_max.19" DOUBLE PRECISION,
    mfcc_mean DOUBLE PRECISION,
    "mfcc_mean.1" DOUBLE PRECISION,
    "mfcc_mean.2" DOUBLE PRECISION,
    "mfcc_mean.3" DOUBLE PRECISION,
    "mfcc_mean.4" DOUBLE PRECISION,
    "mfcc_mean.5" DOUBLE PRECISION,
    "mfcc_mean.6" DOUBLE PRECISION,
    "mfcc_mean.7" DOUBLE PRECISION,
    "mfcc_mean.8" DOUBLE PRECISION,
    "mfcc_mean.9" DOUBLE PRECISION,
    "mfcc_mean.10" DOUBLE PRECISION,
    "mfcc_mean.11" DOUBLE PRECISION,
    "mfcc_mean.12" DOUBLE PRECISION,
    "mfcc_mean.13" DOUBLE PRECISION,
    "mfcc_mean.14" DOUBLE PRECISION,
    "mfcc_mean.15" DOUBLE PRECISION,
    "mfcc_mean.16" DOUBLE PRECISION,
    "mfcc_mean.17" DOUBLE PRECISION,
    "mfcc_mean.18" DOUBLE PRECISION,
    "mfcc_mean.19" DOUBLE PRECISION,
    mfcc_median DOUBLE PRECISION,
    "mfcc_median.1" DOUBLE PRECISION,
    "mfcc_median.2" DOUBLE PRECISION,
    "mfcc_median.3" DOUBLE PRECISION,
    "mfcc_median.4" DOUBLE PRECISION,
    "mfcc_median.5" DOUBLE PRECISION,
    "mfcc_median.6" DOUBLE PRECISION,
    "mfcc_median.7" DOUBLE PRECISION,
    "mfcc_median.8" DOUBLE PRECISION,
    "mfcc_median.9" DOUBLE PRECISION,
    "mfcc_median.10" DOUBLE PRECISION,
    "mfcc_median.11" DOUBLE PRECISION,
    "mfcc_median.12" DOUBLE PRECISION,
    "mfcc_median.13" DOUBLE PRECISION,
    "mfcc_median.14" DOUBLE PRECISION,
    "mfcc_median.15" DOUBLE PRECISION,
    "mfcc_median.16" DOUBLE PRECISION,
    "mfcc_median.17" DOUBLE PRECISION,
    "mfcc_median.18" DOUBLE PRECISION,
    "mfcc_median.19" DOUBLE PRECISION,
    mfcc_min DOUBLE PRECISION,
    "mfcc_min.1" DOUBLE PRECISION,
    "mfcc_min.2" DOUBLE PRECISION,
    "mfcc_min.3" DOUBLE PRECISION,
    "mfcc_min.4" DOUBLE PRECISION,
    "mfcc_min.5" DOUBLE PRECISION,
    "mfcc_min.6" DOUBLE PRECISION,
    "mfcc_min.7" DOUBLE PRECISION,
    "mfcc_min.8" DOUBLE PRECISION,
    "mfcc_min.9" DOUBLE PRECISION,
    "mfcc_min.10" DOUBLE PRECISION,
    "mfcc_min.11" DOUBLE PRECISION,
    "mfcc_min.12" DOUBLE PRECISION,
    "mfcc_min.13" DOUBLE PRECISION,
    "mfcc_min.14" DOUBLE PRECISION,
    "mfcc_min.15" DOUBLE PRECISION,
    "mfcc_min.16" DOUBLE PRECISION,
    "mfcc_min.17" DOUBLE PRECISION,
    "mfcc_min.18" DOUBLE PRECISION,
    "mfcc_min.19" DOUBLE PRECISION,
    mfcc_skew DOUBLE PRECISION,
    "mfcc_skew.1" DOUBLE PRECISION,
    "mfcc_skew.2" DOUBLE PRECISION,
    "mfcc_skew.3" DOUBLE PRECISION,
    "mfcc_skew.4" DOUBLE PRECISION,
    "mfcc_skew.5" DOUBLE PRECISION,
    "mfcc_skew.6" DOUBLE PRECISION,
    "mfcc_skew.7" DOUBLE PRECISION,
    "mfcc_skew.8" DOUBLE PRECISION,
    "mfcc_skew.9" DOUBLE PRECISION,
    "mfcc_skew.10" DOUBLE PRECISION,
    "mfcc_skew.11" DOUBLE PRECISION,
    "mfcc_skew.12" DOUBLE PRECISION,
    "mfcc_skew.13" DOUBLE PRECISION,
    "mfcc_skew.14" DOUBLE PRECISION,
    "mfcc_skew.15" DOUBLE PRECISION,
    "mfcc_skew.16" DOUBLE PRECISION,
    "mfcc_skew.17" DOUBLE PRECISION,
    "mfcc_skew.18" DOUBLE PRECISION,
    "mfcc_skew.19" DOUBLE PRECISION,
    mfcc_std DOUBLE PRECISION,
    "mfcc_std.1" DOUBLE PRECISION,
    "mfcc_std.2" DOUBLE PRECISION,
    "mfcc_std.3" DOUBLE PRECISION,
    "mfcc_std.4" DOUBLE PRECISION,
    "mfcc_std.5" DOUBLE PRECISION,
    "mfcc_std.6" DOUBLE PRECISION,
    "mfcc_std.7" DOUBLE PRECISION,
    "mfcc_std.8" DOUBLE PRECISION,
    "mfcc_std.9" DOUBLE PRECISION,
    "mfcc_std.10" DOUBLE PRECISION,
    "mfcc_std.11" DOUBLE PRECISION,
    "mfcc_std.12" DOUBLE PRECISION,
    "mfcc_std.13" DOUBLE PRECISION,
    "mfcc_std.14" DOUBLE PRECISION,
    "mfcc_std.15" DOUBLE PRECISION,
    "mfcc_std.16" DOUBLE PRECISION,
    "mfcc_std.17" DOUBLE PRECISION,
    "mfcc_std.18" DOUBLE PRECISION,
    "mfcc_std.19" DOUBLE PRECISION,
    rmse_kurtosis DOUBLE PRECISION,
    rmse_max DOUBLE PRECISION,
    rmse_mean DOUBLE PRECISION,
    rmse_median DOUBLE PRECISION,
    rmse_min DOUBLE PRECISION,
    rmse_skew DOUBLE PRECISION,
    rmse_std DOUBLE PRECISION,
    spectral_bandwidth_kurtosis DOUBLE PRECISION,
    spectral_bandwidth_max DOUBLE PRECISION,
    spectral_bandwidth_mean DOUBLE PRECISION,
    spectral_bandwidth_median DOUBLE PRECISION,
    spectral_bandwidth_min DOUBLE PRECISION,
    spectral_bandwidth_skew DOUBLE PRECISION,
    spectral_bandwidth_std DOUBLE PRECISION,
    spectral_centroid_kurtosis DOUBLE PRECISION,
    spectral_centroid_max DOUBLE PRECISION,
    spectral_centroid_mean DOUBLE PRECISION,
    spectral_centroid_median DOUBLE PRECISION,
    spectral_centroid_min DOUBLE PRECISION,
    spectral_centroid_skew DOUBLE PRECISION,
    spectral_centroid_std DOUBLE PRECISION,
    spectral_contrast_kurtosis DOUBLE PRECISION,
    "spectral_contrast_kurtosis.1" DOUBLE PRECISION,
    "spectral_contrast_kurtosis.2" DOUBLE PRECISION,
    "spectral_contrast_kurtosis.3" DOUBLE PRECISION,
    "spectral_contrast_kurtosis.4" DOUBLE PRECISION,
    "spectral_contrast_kurtosis.5" DOUBLE PRECISION,
    "spectral_contrast_kurtosis.6" DOUBLE PRECISION,
    spectral_contrast_max DOUBLE PRECISION,
    "spectral_contrast_max.1" DOUBLE PRECISION,
    "spectral_contrast_max.2" DOUBLE PRECISION,
    "spectral_contrast_max.3" DOUBLE PRECISION,
    "spectral_contrast_max.4" DOUBLE PRECISION,
    "spectral_contrast_max.5" DOUBLE PRECISION,
    "spectral_contrast_max.6" DOUBLE PRECISION,
    spectral_contrast_mean DOUBLE PRECISION,
    "spectral_contrast_mean.1" DOUBLE PRECISION,
    "spectral_contrast_mean.2" DOUBLE PRECISION,
    "spectral_contrast_mean.3" DOUBLE PRECISION,
    "spectral_contrast_mean.4" DOUBLE PRECISION,
    "spectral_contrast_mean.5" DOUBLE PRECISION,
    "spectral_contrast_mean.6" DOUBLE PRECISION,
    spectral_contrast_median DOUBLE PRECISION,
    "spectral_contrast_median.1" DOUBLE PRECISION,
    "spectral_contrast_median.2" DOUBLE PRECISION,
    "spectral_contrast_median.3" DOUBLE PRECISION,
    "spectral_contrast_median.4" DOUBLE PRECISION,
    "spectral_contrast_median.5" DOUBLE PRECISION,
    "spectral_contrast_median.6" DOUBLE PRECISION,
    spectral_contrast_min DOUBLE PRECISION,
    "spectral_contrast_min.1" DOUBLE PRECISION,
    "spectral_contrast_min.2" DOUBLE PRECISION,
    "spectral_contrast_min.3" DOUBLE PRECISION,
    "spectral_contrast_min.4" DOUBLE PRECISION,
    "spectral_contrast_min.5" DOUBLE PRECISION,
    "spectral_contrast_min.6" DOUBLE PRECISION,
    spectral_contrast_skew DOUBLE PRECISION,
    "spectral_contrast_skew.1" DOUBLE PRECISION,
    "spectral_contrast_skew.2" DOUBLE PRECISION,
    "spectral_contrast_skew.3" DOUBLE PRECISION,
    "spectral_contrast_skew.4" DOUBLE PRECISION,
    "spectral_contrast_skew.5" DOUBLE PRECISION,
    "spectral_contrast_skew.6" DOUBLE PRECISION,
    spectral_contrast_std DOUBLE PRECISION,
    "spectral_contrast_std.1" DOUBLE PRECISION,
    "spectral_contrast_std.2" DOUBLE PRECISION,
    "spectral_contrast_std.3" DOUBLE PRECISION,
    "spectral_contrast_std.4" DOUBLE PRECISION,
    "spectral_contrast_std.5" DOUBLE PRECISION,
    "spectral_contrast_std.6" DOUBLE PRECISION,
    spectral_rolloff_kurtosis DOUBLE PRECISION,
    spectral_rolloff_max DOUBLE PRECISION,
    spectral_rolloff_mean DOUBLE PRECISION,
    spectral_rolloff_median DOUBLE PRECISION,
    spectral_rolloff_min DOUBLE PRECISION,
    spectral_rolloff_skew DOUBLE PRECISION,
    spectral_rolloff_std DOUBLE PRECISION,
    tonnetz_kurtosis DOUBLE PRECISION,
    "tonnetz_kurtosis.1" DOUBLE PRECISION,
    "tonnetz_kurtosis.2" DOUBLE PRECISION,
    "tonnetz_kurtosis.3" DOUBLE PRECISION,
    "tonnetz_kurtosis.4" DOUBLE PRECISION,
    "tonnetz_kurtosis.5" DOUBLE PRECISION,
    tonnetz_max DOUBLE PRECISION,
    "tonnetz_max.1" DOUBLE PRECISION,
    "tonnetz_max.2" DOUBLE PRECISION,
    "tonnetz_max.3" DOUBLE PRECISION,
    "tonnetz_max.4" DOUBLE PRECISION,
    "tonnetz_max.5" DOUBLE PRECISION,
    tonnetz_mean DOUBLE PRECISION,
    "tonnetz_mean.1" DOUBLE PRECISION,
    "tonnetz_mean.2" DOUBLE PRECISION,
    "tonnetz_mean.3" DOUBLE PRECISION,
    "tonnetz_mean.4" DOUBLE PRECISION,
    "tonnetz_mean.5" DOUBLE PRECISION,
    tonnetz_median DOUBLE PRECISION,
    "tonnetz_median.1" DOUBLE PRECISION,
    "tonnetz_median.2" DOUBLE PRECISION,
    "tonnetz_median.3" DOUBLE PRECISION,
    "tonnetz_median.4" DOUBLE PRECISION,
    "tonnetz_median.5" DOUBLE PRECISION,
    tonnetz_min DOUBLE PRECISION,
    "tonnetz_min.1" DOUBLE PRECISION,
    "tonnetz_min.2" DOUBLE PRECISION,
    "tonnetz_min.3" DOUBLE PRECISION,
    "tonnetz_min.4" DOUBLE PRECISION,
    "tonnetz_min.5" DOUBLE PRECISION,
    tonnetz_skew DOUBLE PRECISION,
    "tonnetz_skew.1" DOUBLE PRECISION,
    "tonnetz_skew.2" DOUBLE PRECISION,
    "tonnetz_skew.3" DOUBLE PRECISION,
    "tonnetz_skew.4" DOUBLE PRECISION,
    "tonnetz_skew.5" DOUBLE PRECISION,
    tonnetz_std DOUBLE PRECISION,
    "tonnetz_std.1" DOUBLE PRECISION,
    "tonnetz_std.2" DOUBLE PRECISION,
    "tonnetz_std.3" DOUBLE PRECISION,
    "tonnetz_std.4" DOUBLE PRECISION,
    "tonnetz_std.5" DOUBLE PRECISION,
    zcr_kurtosis DOUBLE PRECISION,
    zcr_max DOUBLE PRECISION,
    zcr_mean DOUBLE PRECISION,
    zcr_median DOUBLE PRECISION,
    zcr_min DOUBLE PRECISION,
    zcr_skew DOUBLE PRECISION,
    zcr_std DOUBLE PRECISION
);

\copy stg_features FROM 'T1_analyse_de_donnees/cleaned_data/clean_features.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');

-- Ajouter dynamiquement les colonnes de destination manquantes
DO $$
DECLARE
  rec record;
BEGIN
  FOR rec IN
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'stg_features'
      AND column_name <> 'track_id'
      AND table_schema LIKE 'pg_temp%'
    ORDER BY ordinal_position
  LOOP
    EXECUTE format(
      'ALTER TABLE temporal_feature ADD COLUMN IF NOT EXISTS %I double precision',
      translate(rec.column_name, '.', '')
    );
  END LOOP;
END$$;

DO $$
DECLARE
  col_list text;
  sel_list text;
  upd_list text;
BEGIN
  SELECT string_agg(quote_ident(translate(column_name, '.', '')), ', ' ORDER BY ordinal_position)
    INTO col_list
    FROM information_schema.columns
    WHERE table_name = 'stg_features'
      AND column_name <> 'track_id'
      AND table_schema LIKE 'pg_temp%';

  SELECT string_agg(
           format('%s AS %s', quote_ident(column_name), quote_ident(translate(column_name, '.', ''))),
           ', ' ORDER BY ordinal_position)
    INTO sel_list
    FROM information_schema.columns
    WHERE table_name = 'stg_features'
      AND column_name <> 'track_id'
      AND table_schema LIKE 'pg_temp%';

  SELECT string_agg(
           format('%1$s = EXCLUDED.%1$s', quote_ident(translate(column_name, '.', ''))),
           ', ' ORDER BY ordinal_position)
    INTO upd_list
    FROM information_schema.columns
    WHERE table_name = 'stg_features'
      AND column_name <> 'track_id'
      AND table_schema LIKE 'pg_temp%';

  EXECUTE format(
    'INSERT INTO temporal_feature (track_id, %s) ' ||
    'SELECT m.new_uuid, %s FROM stg_features s ' ||
    'JOIN _legacy_id_map m ON m.old_id = s.track_id AND m.table_name = ''track'' ' ||
    'ON CONFLICT (track_id) DO UPDATE SET %s',
    col_list,
    sel_list,
    upd_list
  );
END$$;
